import { Vocabulary } from './types';

export const lesson8Words: Vocabulary[] = [
  {
    id: 'vocab-8-1',
    word: '包装する',
    reading: 'ほうそうする',
    meaning: 'Đóng gói / Bao bì',
    furigana: '包(ほう)装(そう)する',
    visualClue: 'Một người đang cẩn thận bọc một hộp quà bằng giấy đẹp.',
    soundMnemonic: 'Hô sô (hô hô sô sô) đóng gói.',
    wackyStory: 'Anh chàng cười hô hô khi đóng gói sô-cô-la.',
    kanjiDeconstruction: ['包 (BAO: bao bọc)', '装 (TRANG: trang phục, trang trí)'],
    logicalAnchor: 'Bao bọc lại để trang trí đẹp mắt chính là đóng gói.',
    collocation: 'プレゼントを包装する (Đóng gói quà)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-2',
    word: '仕方',
    reading: 'しかた',
    meaning: 'Cách làm',
    furigana: '仕(し)方(かた)',
    visualClue: 'Một người đang chỉ dẫn cách làm việc.',
    soundMnemonic: 'Shi ka ta (thì ca tạ) - Cách làm.',
    wackyStory: 'Cách làm việc của anh ấy là vừa thi vừa ca tạ.',
    kanjiDeconstruction: ['仕 (SĨ: làm việc)', '方 (PHƯƠNG: cách thức)'],
    logicalAnchor: 'Cách thức để làm việc.',
    collocation: '勉強の仕方 (Cách học)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-3',
    word: '任せる',
    reading: 'まかせる',
    meaning: 'Phó thác / Giao phó',
    furigana: '任(まか)せる',
    visualClue: 'Trao chìa khóa cho người khác.',
    soundMnemonic: 'Mã ca sê - Phó thác việc tính mã cho ca sê.',
    wackyStory: 'Giao phó công việc đếm mã cho anh thu ngân (ca sê).',
    kanjiDeconstruction: ['任 (NHIỆM: trách nhiệm, giao phó)'],
    logicalAnchor: 'Giao trách nhiệm cho ai đó.',
    collocation: '仕事を任せる (Giao phó công việc)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-4',
    word: '箱',
    reading: 'はこ',
    meaning: 'Hộp',
    furigana: '箱(はこ)',
    visualClue: 'Một chiếc hộp các tông.',
    soundMnemonic: 'Hạ cô - Đặt cái hộp xuống.',
    wackyStory: 'Hạ cô gái vào trong một chiếc hộp.',
    kanjiDeconstruction: ['箱 (TƯƠNG: cái hộp)'],
    logicalAnchor: 'Cái hộp làm bằng tre (bộ trúc).',
    collocation: '段ボール箱 (Hộp các tông)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-5',
    word: '包装紙',
    reading: 'ほうそうし',
    meaning: 'Bao bì giấy / Giấy gói',
    furigana: '包(ほう)装(そう)紙(し)',
    visualClue: 'Cuộn giấy dùng để gói quà với nhiều họa tiết.',
    soundMnemonic: 'Hô sô shi - Giấy đóng gói.',
    wackyStory: 'Dùng giấy (shi) để đóng gói (hô sô).',
    kanjiDeconstruction: ['包 (BAO: bao bọc)', '装 (TRANG: trang trí)', '紙 (CHỈ: giấy)'],
    logicalAnchor: 'Giấy dùng để bao bọc và trang trí.',
    collocation: 'きれいな包装紙 (Giấy gói đẹp)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-6',
    word: 'リボン',
    reading: 'りぼん',
    meaning: 'Dây nơ',
    furigana: 'リボン',
    visualClue: 'Sợi dây ruy băng thắt nơ trên hộp quà.',
    soundMnemonic: 'Ri bôn - Ribbon (Ruy băng).',
    wackyStory: 'Dây nơ ruy băng.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Ribbon.',
    collocation: 'リボンを結ぶ (Thắt nơ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-7',
    word: 'かける',
    reading: 'かける',
    meaning: 'Treo lên / Đính (đính nơ)',
    furigana: 'かける',
    visualClue: 'Treo áo lên móc hoặc đính nơ lên hộp.',
    soundMnemonic: 'Ca kê rự - Ca kê rự lên móc.',
    wackyStory: 'Ca kê rự cái nơ lên hộp.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Hành động gắn, treo, đính vào một vật khác.',
    collocation: 'リボンをかける (Đính nơ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-8',
    word: 'ラッピングする',
    reading: 'らっぴんぐする',
    meaning: 'Gói / Bao bọc',
    furigana: 'ラッピングする',
    visualClue: 'Bọc một vật dụng bằng màng bọc.',
    soundMnemonic: 'Ráp ping - Wrapping.',
    wackyStory: 'Gói quà (Wrapping).',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Wrapping.',
    collocation: 'プレゼントをラッピングする (Gói quà)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-9',
    word: 'グッズ',
    reading: 'ぐっず',
    meaning: 'Hàng hóa / Hàng',
    furigana: 'グッズ',
    visualClue: 'Các món đồ lưu niệm, áo thun, móc khóa của một ban nhạc.',
    soundMnemonic: 'Gút zự - Goods.',
    wackyStory: 'Hàng hóa tốt (Goods).',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Goods.',
    collocation: 'キャラクターグッズ (Hàng hóa nhân vật)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-10',
    word: '貴族',
    reading: 'きぞく',
    meaning: 'Quý tộc / Vương giả',
    furigana: '貴(き)族(ぞく)',
    visualClue: 'Người mặc trang phục sang trọng, sống trong lâu đài.',
    soundMnemonic: 'Ki zô kự - Quý tộc đi vào khu di tích.',
    wackyStory: 'Quý tộc đi tìm kỷ vật của bộ tộc.',
    kanjiDeconstruction: ['貴 (QUÝ: quý giá, cao quý)', '族 (TỘC: gia tộc)'],
    logicalAnchor: 'Gia tộc có địa vị cao quý.',
    collocation: '貴族の生活 (Cuộc sống quý tộc)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-11',
    word: 'さらす',
    reading: 'さらす',
    meaning: 'Dấn / Phơi bày',
    furigana: 'さらす',
    visualClue: 'Phơi đồ ra ánh nắng mặt trời hoặc dấn thân vào nguy hiểm.',
    soundMnemonic: 'Sa ra sư - Sợ ra sư phơi bày.',
    wackyStory: 'Sa vào vũng bùn rồi phơi ra ánh nắng.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Mang ra ngoài, để lộ ra.',
    collocation: '危険に身をさらす (Dấn thân vào nguy hiểm)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-12',
    word: '当時',
    reading: 'とうじ',
    meaning: 'Lúc đó / Thời đó',
    furigana: '当(とう)時(じ)',
    visualClue: 'Một bức ảnh đen trắng từ ngày xưa.',
    soundMnemonic: 'Tô ji - Lúc đó tôi ăn tô mì.',
    wackyStory: 'Thời đó, tô mì chỉ có giá 2 nghìn.',
    kanjiDeconstruction: ['当 (ĐƯƠNG: lúc, khi)', '時 (THỜI: thời gian)'],
    logicalAnchor: 'Thời điểm xảy ra sự việc.',
    collocation: '当時の思い出 (Kỷ niệm thời đó)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-13',
    word: '高価な',
    reading: 'こうかな',
    meaning: 'Đắt giá / Đắt tiền',
    furigana: '高(こう)価(か)な',
    visualClue: 'Một món trang sức lấp lánh với bảng giá cao.',
    soundMnemonic: 'Cô ca - Cô ca sĩ đeo trang sức đắt tiền.',
    wackyStory: 'Cô ca sĩ mua một chiếc nhẫn vô cùng đắt giá.',
    kanjiDeconstruction: ['高 (CAO: cao)', '価 (GIÁ: giá cả)'],
    logicalAnchor: 'Giá cả cao.',
    collocation: '高価な宝石 (Đá quý đắt tiền)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-14',
    word: '表れ',
    reading: 'あらわれ',
    meaning: 'Biểu hiện',
    furigana: '表(あらわ)れ',
    visualClue: 'Biểu cảm trên khuôn mặt hoặc một hành động chứng minh điều gì đó.',
    soundMnemonic: 'A ra wa rê - A ra là biểu hiện.',
    wackyStory: 'A ra là biểu hiện của sự tức giận.',
    kanjiDeconstruction: ['表 (BIỂU: thể hiện ra ngoài)'],
    logicalAnchor: 'Sự thể hiện ra bên ngoài.',
    collocation: '喜びの表れ (Biểu hiện của sự vui mừng)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-15',
    word: '破る',
    reading: 'やぶる',
    meaning: 'Rách / Làm rách / Phá vỡ',
    furigana: '破(やぶ)る',
    visualClue: 'Một tờ giấy bị xé rách làm đôi.',
    soundMnemonic: 'Ya bư rự - Xé rách cái yếm.',
    wackyStory: 'Bị rách áo vì vướng vào cành cây.',
    kanjiDeconstruction: ['破 (PHÁ: phá vỡ, làm rách)'],
    logicalAnchor: 'Dùng sức để làm hỏng, xé rách một vật.',
    collocation: '紙を破る (Xé rách giấy)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-16',
    word: 'ブックカバー',
    reading: 'ぶっくかばー',
    meaning: 'Bọc sách / Vỏ bọc sách',
    furigana: 'ブックカバー',
    visualClue: 'Một lớp áo bọc ngoài quyển sách để bảo vệ.',
    soundMnemonic: 'Bút kự ca ba - Book cover.',
    wackyStory: 'Cái bọc sách (Book cover).',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Book cover.',
    collocation: 'ブックカバーをつける (Bọc sách lại)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-17',
    word: 'あるいは',
    reading: 'あるいは',
    meaning: 'Hoặc / Hoặc là',
    furigana: 'あるいは',
    visualClue: 'Hai mũi tên chỉ về hai hướng khác nhau.',
    soundMnemonic: 'A rưi wa - A rưi hoặc là B.',
    wackyStory: 'Chọn A rưi hoặc là B rưi.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Dùng để nối hai lựa chọn.',
    collocation: '電車、あるいはバスで行く (Đi bằng tàu điện hoặc xe buýt)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-18',
    word: '含める',
    reading: 'ふくめる',
    meaning: 'Bao gồm',
    furigana: '含(ふく)める',
    visualClue: 'Cho một vật nhỏ vào trong một vật lớn hơn.',
    soundMnemonic: 'Phư cư mê rự - Phải cứ mê rự mới bao gồm.',
    wackyStory: 'Bao gồm cả phí vận chuyển.',
    kanjiDeconstruction: ['含 (HÀM: ngậm, bao gồm)'],
    logicalAnchor: 'Cho vào bên trong.',
    collocation: '税金を含める (Bao gồm tiền thuế)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-19',
    word: 'ぐっと',
    reading: 'ぐっと',
    meaning: 'Vững chắc / Kiên cố / Hơn nhiều',
    furigana: 'ぐっと',
    visualClue: 'Hành động nắm chặt tay lại.',
    soundMnemonic: 'Gút tộ - Nắm chặt tay gút tộ.',
    wackyStory: 'Trở nên vững chắc hơn nhiều.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ tượng thanh/tượng hình chỉ sự thay đổi lớn hoặc dùng lực mạnh.',
    collocation: 'ぐっと良くなる (Trở nên tốt hơn hẳn)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-20',
    word: '許可する',
    reading: 'きょかする',
    meaning: 'Cho phép',
    furigana: '許(きょ)可(か)する',
    visualClue: 'Con dấu đóng chữ OK lên một tờ đơn.',
    soundMnemonic: 'Kyo ca - Cho ca hát.',
    wackyStory: 'Giám đốc cho phép cô ấy ca hát.',
    kanjiDeconstruction: ['許 (HỨA: cho phép, đồng ý)', '可 (KHẢ: có thể)'],
    logicalAnchor: 'Đồng ý cho việc gì đó có thể diễn ra.',
    collocation: '外出を許可する (Cho phép ra ngoài)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-21',
    word: '～末',
    reading: '～まつ',
    meaning: 'Cuối ~ (Ví dụ: cuối tháng)',
    furigana: '～末(まつ)',
    visualClue: 'Phần cuối của một cuốn lịch.',
    soundMnemonic: 'Ma tsu - Cuối cùng thì ma cũng tu.',
    wackyStory: 'Đến cuối tháng mới nhận lương.',
    kanjiDeconstruction: ['末 (MẠT: phần cuối)'],
    logicalAnchor: 'Phần kết thúc của một khoảng thời gian.',
    collocation: '来月末 (Cuối tháng sau)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-22',
    word: '全く',
    reading: 'まったく',
    meaning: 'Toàn bộ / Tất cả / Hoàn toàn',
    furigana: '全(まった)く',
    visualClue: 'Một tờ giấy trắng tinh, không có gì cả.',
    soundMnemonic: 'Mạt ta cự - Hoàn toàn mạt ta cự.',
    wackyStory: 'Hoàn toàn không biết gì.',
    kanjiDeconstruction: ['全 (TOÀN: hoàn toàn)'],
    logicalAnchor: 'Phủ định hoàn toàn (khi đi với đuôi phủ định).',
    collocation: '全くわからない (Hoàn toàn không hiểu)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-23',
    word: '同僚',
    reading: 'どうりょう',
    meaning: 'Bạn đồng nghiệp',
    furigana: '同(どう)僚(りょう)',
    visualClue: 'Hai người mặc đồ công sở đập tay nhau.',
    soundMnemonic: 'Đô ryô - Đồng lương.',
    wackyStory: 'Đồng nghiệp là người nhận đồng lương giống mình.',
    kanjiDeconstruction: ['同 (ĐỒNG: cùng)', '僚 (LIÊU: đồng nghiệp)'],
    logicalAnchor: 'Người làm cùng trong một công ty.',
    collocation: '会社の同僚 (Đồng nghiệp trong công ty)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-24',
    word: 'かける',
    reading: 'かける',
    meaning: 'Làm, gây ra (Làm phiền)',
    furigana: 'かける',
    visualClue: 'Gây rắc rối cho người khác.',
    soundMnemonic: 'Ca kê rự - Ca kê rự rắc rối.',
    wackyStory: 'Gây ra phiền phức.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Tác động lên người khác (thường mang nghĩa tiêu cực trong cụm này).',
    collocation: '迷惑をかける (Làm phiền)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-25',
    word: '回収する',
    reading: 'かいしゅうする',
    meaning: 'Thu hồi / Thu lại',
    furigana: '回(かい)収(しゅう)する',
    visualClue: 'Xe rác đi thu gom phế liệu.',
    soundMnemonic: 'Cai shiu - Thu hồi cái khiên.',
    wackyStory: 'Thu hồi các sản phẩm bị lỗi.',
    kanjiDeconstruction: ['回 (HỒI: quay lại)', '収 (THU: thu thập)'],
    logicalAnchor: 'Thu thập đồ vật mang về.',
    collocation: 'アンケートを回収する (Thu hồi phiếu điều tra)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-26',
    word: '置き場',
    reading: 'おきば',
    meaning: 'Chỗ để / Nơi đặt',
    furigana: '置(お)き場(ば)',
    visualClue: 'Bãi đỗ xe đạp.',
    soundMnemonic: 'Ô ki ba - Nơi để cái ô ki ba.',
    wackyStory: 'Chỗ để xe đạp ở góc đường.',
    kanjiDeconstruction: ['置 (TRÍ: đặt để)', '場 (TRƯỜNG: địa điểm)'],
    logicalAnchor: 'Nơi dùng để cất giữ đồ đạc.',
    collocation: '自転車置き場 (Chỗ để xe đạp)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-27',
    word: '色違い',
    reading: 'いろちがい',
    meaning: 'Màu khác',
    furigana: '色(いろ)違(ちが)い',
    visualClue: 'Hai chiếc áo giống hệt nhau nhưng khác màu.',
    soundMnemonic: 'I rô chi gai - Màu bị sai.',
    wackyStory: 'Mua nhầm chiếc áo màu khác.',
    kanjiDeconstruction: ['色 (SẮC: màu sắc)', '違 (VI: khác, sai)'],
    logicalAnchor: 'Màu sắc khác biệt.',
    collocation: '色違いのシャツ (Áo sơ mi khác màu)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-28',
    word: '申し訳ありません',
    reading: 'もうしわけありません',
    meaning: 'Xin lỗi (cách nói lịch sự)',
    furigana: '申(もう)し訳(わけ)ありません',
    visualClue: 'Nhân viên cúi gập người xin lỗi khách hàng.',
    soundMnemonic: 'Mô shi wa kê - Lời xin lỗi chân thành.',
    wackyStory: 'Nhân viên xin lỗi vì lỡ làm đổ nước.',
    kanjiDeconstruction: ['申 (THÂN: xưng tên, nói)', '訳 (DỊCH: lý do)'],
    logicalAnchor: 'Không có lý do gì để bào chữa -> Xin lỗi.',
    collocation: '遅れて申し訳ありません (Xin lỗi vì tôi đến trễ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-29',
    word: '朝礼',
    reading: 'ちょうれい',
    meaning: 'Lễ buổi sáng (Họp đầu giờ)',
    furigana: '朝(ちょう)礼(れい)',
    visualClue: 'Nhân viên xếp hàng nghe sếp phổ biến công việc buổi sáng.',
    soundMnemonic: 'Chô rê - Buổi họp buổi sáng.',
    wackyStory: 'Mọi người tập trung để họp buổi sáng.',
    kanjiDeconstruction: ['朝 (TRIÊU: buổi sáng)', '礼 (LỄ: nghi lễ)'],
    logicalAnchor: 'Nghi thức hoặc buổi họp vào buổi sáng.',
    collocation: '朝礼を行う (Tổ chức họp đầu giờ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-30',
    word: 'オープンキャンパス',
    reading: 'おーぷんきゃんぱす',
    meaning: 'Ngày hội mở cửa tham quan trường đại học',
    furigana: 'オープンキャンパス',
    visualClue: 'Cổng trường đại học mở rộng chào đón học sinh cấp 3.',
    soundMnemonic: 'Ô pưn kyan pa sư - Open campus.',
    wackyStory: 'Tham gia ngày hội Open campus để tìm hiểu trường.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Open campus.',
    collocation: 'オープンキャンパスに参加する (Tham gia ngày hội tham quan trường)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-31',
    word: '一時帰国',
    reading: 'いちじきこく',
    meaning: 'Về nước tạm thời',
    furigana: '一(いち)時(じ)帰(き)国(こく)',
    visualClue: 'Xách vali lên máy bay về quê ăn Tết rồi quay lại.',
    soundMnemonic: 'I chi ji ki cô cự - Về nước 1 thời gian.',
    wackyStory: 'Về nước một thời gian ngắn rồi lại sang Nhật.',
    kanjiDeconstruction: ['一 (NHẤT: một)', '時 (THỜI: thời gian)', '帰 (QUY: trở về)', '国 (QUỐC: đất nước)'],
    logicalAnchor: 'Trở về nước trong một thời gian.',
    collocation: '一時帰国する (Về nước tạm thời)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-32',
    word: '帰国する',
    reading: 'きこくする',
    meaning: 'Về nước',
    furigana: '帰(き)国(こく)する',
    visualClue: 'Hạ cánh xuống sân bay quê nhà.',
    soundMnemonic: 'Ki cô cự - Về nước.',
    wackyStory: 'Kết thúc chuyến du học và về nước.',
    kanjiDeconstruction: ['帰 (QUY: trở về)', '国 (QUỐC: đất nước)'],
    logicalAnchor: 'Quay trở về quốc gia của mình.',
    collocation: '日本から帰国する (Về nước từ Nhật Bản)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-33',
    word: 'メッセージ',
    reading: 'めっせーじ',
    meaning: 'Tin nhắn',
    furigana: 'メッセージ',
    visualClue: 'Một tin nhắn trên điện thoại.',
    soundMnemonic: 'Mết xê di.',
    wackyStory: 'Tin nhắn từ phương xa.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Message.',
    collocation: 'メッセージを送る (Gửi tin nhắn)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-34',
    word: '一筆箋',
    reading: 'いっぴつせん',
    meaning: 'Giấy ippitsusen (giấy thon dài viết thư ngắn)',
    furigana: '一(いっ)筆(ぴつ)箋(せん)',
    visualClue: 'Một xấp giấy dài, hẹp dùng để viết lời nhắn.',
    soundMnemonic: 'Ít pi tsu sen.',
    wackyStory: 'Dùng một nét bút viết lên giấy.',
    kanjiDeconstruction: ['一 (NHẤT: một)', '筆 (BÚT: bút)', '箋 (TIÊN: giấy)'],
    logicalAnchor: 'Giấy dùng để viết một vài nét chữ.',
    collocation: '一筆箋に書く (Viết vào giấy ippitsusen)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-35',
    word: '伝わる',
    reading: 'つたわる',
    meaning: 'Truyền, truyền đạt',
    furigana: '伝(つた)わる',
    visualClue: 'Tin tức lan truyền từ người này sang người khác.',
    soundMnemonic: 'Tsu ta wa rự.',
    wackyStory: 'Thông tin truyền đi nhanh chóng.',
    kanjiDeconstruction: ['伝 (TRUYỀN: truyền đạt)'],
    logicalAnchor: 'Sự truyền đạt.',
    collocation: '気持ちが伝わる (Truyền đạt cảm xúc)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-36',
    word: '便箋',
    reading: 'びんせん',
    meaning: 'Giấy viết thư',
    furigana: '便(びん)箋(せん)',
    visualClue: 'Tờ giấy có kẻ dòng để viết thư.',
    soundMnemonic: 'Bin sen.',
    wackyStory: 'Giấy tiện lợi để viết thư.',
    kanjiDeconstruction: ['便 (TIỆN: tiện lợi)', '箋 (TIÊN: giấy)'],
    logicalAnchor: 'Giấy dùng để viết thư từ.',
    collocation: '便箋に手紙を書く (Viết thư vào giấy viết thư)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-37',
    word: '本題',
    reading: 'ほんだい',
    meaning: 'Chủ đề chính',
    furigana: '本(ほん)題(だい)',
    visualClue: 'Phần chữ to nhất trên trang giấy nêu rõ ý chính.',
    soundMnemonic: 'Hôn đai.',
    wackyStory: 'Chủ đề chính của cuốn sách là về cái đai.',
    kanjiDeconstruction: ['本 (BẢN: chính)', '題 (ĐỀ: chủ đề)'],
    logicalAnchor: 'Vấn đề cốt lõi, chính yếu.',
    collocation: '本題に入る (Đi vào vấn đề chính)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-38',
    word: '手書き',
    reading: 'てがき',
    meaning: 'Viết tay',
    furigana: '手(て)書(が)き',
    visualClue: 'Bàn tay đang cầm bút viết trên giấy.',
    soundMnemonic: 'Tê ga ki.',
    wackyStory: 'Bức thư này được viết tay hoàn toàn.',
    kanjiDeconstruction: ['手 (THỦ: tay)', '書 (THƯ: viết)'],
    logicalAnchor: 'Dùng tay để viết.',
    collocation: '手書きの手紙 (Bức thư viết tay)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-39',
    word: '一言',
    reading: 'ひとこと',
    meaning: 'Một câu / một lời',
    furigana: '一(ひと)言(こと)',
    visualClue: 'Bong bóng thoại có chữ ngắn.',
    soundMnemonic: 'Hi tô cô tô.',
    wackyStory: 'Nói một lời ngắn gọn.',
    kanjiDeconstruction: ['一 (NHẤT: một)', '言 (NGÔN: lời nói)'],
    logicalAnchor: 'Chỉ một lời nói.',
    collocation: '一言添える (Thêm vào một lời nhắn)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-40',
    word: '添える',
    reading: 'そえる',
    meaning: 'Thêm vào / kèm theo',
    furigana: '添(そ)える',
    visualClue: 'Kẹp thêm một tấm thiệp nhỏ vào bó hoa.',
    soundMnemonic: 'Sô ê rự.',
    wackyStory: 'Sợ ế nên đính kèm quà tặng.',
    kanjiDeconstruction: ['添 (THIÊM: thêm vào)'],
    logicalAnchor: 'Hành động bổ sung thêm vào.',
    collocation: '手紙を添える (Đính kèm bức thư)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-41',
    word: '思い',
    reading: 'おもい',
    meaning: 'Suy nghĩ',
    furigana: '思(おも)い',
    visualClue: 'Bong bóng suy nghĩ trên đầu.',
    soundMnemonic: 'Ô môi.',
    wackyStory: 'Suy nghĩ về tương lai.',
    kanjiDeconstruction: ['思 (TƯ: suy nghĩ)'],
    logicalAnchor: 'Những điều nằm trong tâm trí.',
    collocation: '思いを伝える (Truyền đạt suy nghĩ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-42',
    word: '印刷する',
    reading: 'いんさつする',
    meaning: 'In ấn',
    furigana: '印(いん)刷(さつ)する',
    visualClue: 'Máy in đang chạy ra giấy.',
    soundMnemonic: 'In sa tsu.',
    wackyStory: 'In sách ra để đọc.',
    kanjiDeconstruction: ['印 (ẤN: in)', '刷 (LOÁT: chải, in)'],
    logicalAnchor: 'Sử dụng máy móc để in chữ lên giấy.',
    collocation: '資料を印刷する (In tài liệu)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-43',
    word: '縦',
    reading: 'たて',
    meaning: 'Chiều dọc',
    furigana: '縦(たて)',
    visualClue: 'Mũi tên chỉ từ trên xuống dưới.',
    soundMnemonic: 'Ta tê.',
    wackyStory: 'Đường kẻ dọc.',
    kanjiDeconstruction: ['縦 (TUNG: chiều dọc)'],
    logicalAnchor: 'Hướng từ trên xuống hoặc ngược lại.',
    collocation: '縦に切る (Cắt theo chiều dọc)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-44',
    word: '～センチ',
    reading: '～せんち',
    meaning: 'Xen-ti-mét',
    furigana: '～センチ',
    visualClue: 'Thước kẻ.',
    soundMnemonic: 'Sen chi.',
    wackyStory: 'Đo độ dài bằng cm.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Centimeter.',
    collocation: '長さは18センチ (Độ dài là 18cm)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-45',
    word: '細長い',
    reading: 'ほそながい',
    meaning: 'Thon dài',
    furigana: '細(ほそ)長(なが)い',
    visualClue: 'Một dải ruy băng mảnh và dài.',
    soundMnemonic: 'Hô sô na gai.',
    wackyStory: 'Một vật thon và dài.',
    kanjiDeconstruction: ['細 (TẾ: mảnh, nhỏ)', '長 (TRƯỜNG: dài)'],
    logicalAnchor: 'Vừa mảnh (nhỏ) vừa dài.',
    collocation: '細長い形 (Hình dạng thon dài)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-46',
    word: '堅い',
    reading: 'かたい',
    meaning: 'Cứng, trang trọng',
    furigana: '堅(かた)い',
    visualClue: 'Một người mặc vest đi đứng nghiêm trang.',
    soundMnemonic: 'Ka tai.',
    wackyStory: 'Cách nói chuyện rất cứng nhắc, trang trọng.',
    kanjiDeconstruction: ['堅 (KIÊN: vững chắc, cứng)'],
    logicalAnchor: 'Sự trang trọng, nghiêm túc.',
    collocation: '堅い表現 (Cách diễn đạt trang trọng)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-47',
    word: '贈り物',
    reading: 'おくりもの',
    meaning: 'Quà tặng',
    furigana: '贈(おく)り物(もの)',
    visualClue: 'Hộp quà có nơ.',
    soundMnemonic: 'Ô cư ri mô nô.',
    wackyStory: 'Vật được gửi tặng.',
    kanjiDeconstruction: ['贈 (TẶNG: tặng)', '物 (VẬT: đồ vật)'],
    logicalAnchor: 'Đồ vật dùng để làm quà tặng.',
    collocation: '贈り物を開ける (Mở quà)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-48',
    word: 'お世話になっています',
    reading: 'おせわになっています',
    meaning: 'Cảm ơn vì đã giúp đỡ / Đang được quan tâm',
    furigana: 'お世(せ)話(わ)になっています',
    visualClue: 'Cúi đầu chào kính trọng.',
    soundMnemonic: 'Ô sê wa ni nat tê i ma sư.',
    wackyStory: 'Xin lỗi vì làm phiền và cảm ơn đã chăm sóc.',
    kanjiDeconstruction: ['世 (THẾ: thế giới, đời)', '話 (THOẠI: câu chuyện)'],
    logicalAnchor: 'Cách nói lịch sự cảm ơn sự hỗ trợ của ai đó.',
    collocation: 'いつもお世話になっています (Luôn cảm ơn vì sự giúp đỡ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-49',
    word: '気が利く',
    reading: 'きがきく',
    meaning: 'Chu đáo / Quan tâm',
    furigana: '気(き)が利(き)く',
    visualClue: 'Một người mang trà đến trước khi bạn kịp yêu cầu.',
    soundMnemonic: 'Ki ga ki cự.',
    wackyStory: 'Sự nhạy bén trong cách ứng xử.',
    kanjiDeconstruction: ['気 (KHÍ: tinh thần, tâm trí)', '利 (LỢI: tiện lợi)'],
    logicalAnchor: 'Tâm trí luôn hoạt động hiệu quả, tinh tế.',
    collocation: '気が利く人 (Người chu đáo)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-50',
    word: '先日',
    reading: 'せんじつ',
    meaning: 'Hôm trước / Vài ngày trước',
    furigana: '先(せん)日(じつ)',
    visualClue: 'Chỉ tay về tờ lịch của ngày hôm trước.',
    soundMnemonic: 'Sen ji tsu.',
    wackyStory: 'Sự việc xảy ra vài hôm trước.',
    kanjiDeconstruction: ['先 (TIÊN: trước)', '日 (NHẬT: ngày)'],
    logicalAnchor: 'Ngày ở phía trước (trong quá khứ).',
    collocation: '先日はありがとうございました (Cảm ơn vì việc hôm trước)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-51',
    word: '近況',
    reading: 'きんきょう',
    meaning: 'Tình trạng gần đây',
    furigana: '近(きん)況(きょう)',
    visualClue: 'Kể cho bạn bè nghe chuyện xảy ra dạo này.',
    soundMnemonic: 'Kin kyo.',
    wackyStory: 'Tình hình hiện tại.',
    kanjiDeconstruction: ['近 (CẬN: gần)', '況 (HUỐNG: tình trạng)'],
    logicalAnchor: 'Tình trạng ở thời điểm gần đây.',
    collocation: '近況を報告する (Báo cáo tình hình gần đây)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-52',
    word: 'お久しぶりです',
    reading: 'おひさしぶりです',
    meaning: 'Lâu không gặp',
    furigana: 'お久(ひさ)しぶりです',
    visualClue: 'Hai người bạn gặp lại nhau sau nhiều năm.',
    soundMnemonic: 'Ô hi sa shi bư ri đê sư.',
    wackyStory: 'Lời chào sau thời gian dài không gặp.',
    kanjiDeconstruction: ['久 (CỬU: lâu dài)'],
    logicalAnchor: 'Đã lâu rồi (mới gặp).',
    collocation: '先生、お久しぶりです (Thầy ơi, đã lâu không gặp)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-53',
    word: '相変わらず',
    reading: 'あいかわらず',
    meaning: 'Không thay đổi / Như mọi khi',
    furigana: '相(あい)変(か)わらず',
    visualClue: 'Một người vẫn giữ thói quen uống trà mỗi sáng trong 10 năm.',
    soundMnemonic: 'Ai ka wa ra zự.',
    wackyStory: 'Mọi thứ vẫn y như cũ.',
    kanjiDeconstruction: ['相 (TƯƠNG: cùng, lẫn nhau)', '変 (BIẾN: thay đổi)'],
    logicalAnchor: 'Tình trạng không có sự biến đổi.',
    collocation: '相変わらずお元気ですね (Bạn vẫn khỏe như mọi khi nhỉ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-54',
    word: '気に入る',
    reading: 'きにいる',
    meaning: 'Yêu thích / Ưa thích',
    furigana: '気(き)に入(い)る',
    visualClue: 'Mắt sáng lên khi nhìn thấy món đồ ưng ý.',
    soundMnemonic: 'Ki ni i rự.',
    wackyStory: 'Một món đồ lọt vào tâm trí.',
    kanjiDeconstruction: ['気 (KHÍ: tâm trạng)', '入 (NHẬP: vào)'],
    logicalAnchor: 'Điều gì đó đi vào tâm trí mình, tạo ấn tượng tốt.',
    collocation: 'この服を気に入る (Thích bộ quần áo này)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-55',
    word: '出産する',
    reading: 'しゅっさんする',
    meaning: 'Sinh sản (sinh em bé)',
    furigana: '出(しゅっ)産(さん)する',
    visualClue: 'Một em bé mới sinh.',
    soundMnemonic: 'Shụt san.',
    wackyStory: 'Sự ra đời của một đứa trẻ.',
    kanjiDeconstruction: ['出 (XUẤT: ra)', '産 (SẢN: sinh ra)'],
    logicalAnchor: 'Sinh ra một đứa trẻ.',
    collocation: '無事に出産する (Sinh đẻ mẹ tròn con vuông)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-56',
    word: '機械',
    reading: 'きかい',
    meaning: 'Máy móc',
    furigana: '機(き)械(かい)',
    visualClue: 'Bánh răng và các bộ phận của máy.',
    soundMnemonic: 'Ki cai.',
    wackyStory: 'Hệ thống máy móc phức tạp.',
    kanjiDeconstruction: ['機 (CƠ: bộ máy)', '械 (GIỚI: máy móc)'],
    logicalAnchor: 'Thiết bị hoạt động bằng máy.',
    collocation: '新しい機械を導入する (Đưa máy móc mới vào sử dụng)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-57',
    word: '済ませる',
    reading: 'すませる',
    meaning: 'Kết thúc / Giải quyết xong xuôi',
    furigana: '済(す)ませる',
    visualClue: 'Đánh dấu tích vào công việc cuối cùng trong ngày.',
    soundMnemonic: 'Sư ma sê rự.',
    wackyStory: 'Hoàn thành công việc.',
    kanjiDeconstruction: ['済 (TẾ: kết thúc)'],
    logicalAnchor: 'Làm cho xong việc gì đó.',
    collocation: '宿題を済ませる (Giải quyết xong bài tập)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-58',
    word: 'ちょっとした',
    reading: 'ちょっとした',
    meaning: 'Một chút / Nho nhỏ',
    furigana: 'ちょっとした',
    visualClue: 'Cử chỉ đưa tay diễn tả một lượng rất nhỏ.',
    soundMnemonic: 'Chốt tô shi ta.',
    wackyStory: 'Một món quà nhỏ.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Chỉ quy mô, mức độ nhỏ.',
    collocation: 'ちょっとしたプレゼント (Món quà nho nhỏ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-59',
    word: 'ラストオーダー',
    reading: 'らすとおーだー',
    meaning: 'Gọi món lần cuối (Last order)',
    furigana: 'ラストオーダー',
    visualClue: 'Nhân viên phục vụ hỏi khách có muốn gọi thêm đồ trước khi đóng cửa.',
    soundMnemonic: 'Ra sư tô ô đa.',
    wackyStory: 'Lần gọi món cuối cùng.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Last order.',
    collocation: 'ラストオーダーの時間を聞く (Hỏi thời gian gọi món cuối cùng)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-60',
    word: '追加する',
    reading: 'ついかする',
    meaning: 'Thêm, gọi thêm món',
    furigana: '追(つい)加(か)する',
    visualClue: 'Khách hàng đưa tay vẫy nhân viên để gọi thêm đồ ăn.',
    soundMnemonic: 'Tsu i ca.',
    wackyStory: 'Gọi thêm một ly trà.',
    kanjiDeconstruction: ['追 (TRUY: đuổi theo)', '加 (GIA: thêm vào)'],
    logicalAnchor: 'Thêm vào những gì đã có.',
    collocation: '料理を追加する (Gọi thêm đồ ăn)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-61',
    word: '生ビール',
    reading: 'なまびーる',
    meaning: 'Bia tươi',
    furigana: '生(なま)ビール',
    visualClue: 'Ly bia mát lạnh với lớp bọt trắng phía trên.',
    soundMnemonic: 'Na ma bi rự.',
    wackyStory: 'Bia tươi mới rót.',
    kanjiDeconstruction: ['生 (SINH: sống, tươi)'],
    logicalAnchor: 'Bia chưa qua tiệt trùng.',
    collocation: '生ビールを注文する (Gọi bia tươi)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-62',
    word: 'サプライズパーティー',
    reading: 'さぷらいずぱーてぃー',
    meaning: 'Bữa tiệc bất ngờ',
    furigana: 'サプライズパーティー',
    visualClue: 'Mọi người nhảy ra khỏi chỗ nấp và hét lên chúc mừng sinh nhật.',
    soundMnemonic: 'Sa pư rai zư pa ti.',
    wackyStory: 'Bữa tiệc mang lại sự bất ngờ.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Surprise party.',
    collocation: 'サプライズパーティーを開く (Tổ chức tiệc bất ngờ)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-63',
    word: '愚痴',
    reading: 'ぐち',
    meaning: 'Than thở, cằn nhằn',
    furigana: '愚(ぐ)痴(ち)',
    visualClue: 'Một người đang nhăn nhó và phàn nàn về công việc.',
    soundMnemonic: 'Gu chi.',
    wackyStory: 'Cứ than thở mãi.',
    kanjiDeconstruction: ['愚 (NGU: ngu ngốc)', '痴 (SI: ngốc nghếch)'],
    logicalAnchor: 'Những lời phàn nàn vô ích.',
    collocation: '愚痴をこぼす (Than vãn, cằn nhằn)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-64',
    word: '渋滞する',
    reading: 'じゅうたいする',
    meaning: 'Tắc nghẽn, kẹt xe',
    furigana: '渋(じゅう)滞(たい)する',
    visualClue: 'Hàng dài ô tô đứng im trên đường phố.',
    soundMnemonic: 'Jyu tai.',
    wackyStory: 'Giao thông bị đình trệ.',
    kanjiDeconstruction: ['渋 (SÁP: chát, trệ)', '滞 (TRỆ: đình trệ)'],
    logicalAnchor: 'Xe cộ lưu thông chậm chạp.',
    collocation: '道が渋滞している (Đường đang bị kẹt xe)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-65',
    word: '帰宅する',
    reading: 'きたくする',
    meaning: 'Về nhà',
    furigana: '帰(き)宅(たく)する',
    visualClue: 'Một người vừa bước vào cửa nhà mình.',
    soundMnemonic: 'Ki ta cự.',
    wackyStory: 'Quay trở về ngôi nhà của mình.',
    kanjiDeconstruction: ['帰 (QUY: trở về)', '宅 (TRẠCH: nhà)'],
    logicalAnchor: 'Quay về nhà.',
    collocation: '急いで帰宅する (Vội vàng về nhà)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-66',
    word: '久しぶりな',
    reading: 'ひさしぶりな',
    meaning: 'Lâu rồi',
    furigana: '久(ひさ)しぶりな',
    visualClue: 'Gặp lại một người bạn cũ.',
    soundMnemonic: 'Hi sa shi bư ri.',
    wackyStory: 'Đã lâu không gặp.',
    kanjiDeconstruction: ['久 (CỬU: lâu dài)'],
    logicalAnchor: 'Thời gian đã trôi qua lâu.',
    collocation: '久しぶりな友達 (Người bạn đã lâu không gặp)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-67',
    word: '壊す',
    reading: 'こわす',
    meaning: 'Làm hại (Làm hại cơ thể, ảnh hưởng xấu đến sức khỏe)',
    furigana: '壊(こわ)す',
    visualClue: 'Một người đang bị ốm vì làm việc quá sức.',
    soundMnemonic: 'Ko wa sư.',
    wackyStory: 'Làm hỏng sức khỏe.',
    kanjiDeconstruction: ['壊 (HOẠI: phá hỏng)'],
    logicalAnchor: 'Làm hỏng hoặc gây tổn hại.',
    collocation: '体を壊す (Làm hại cơ thể/sức khỏe)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-68',
    word: '割る',
    reading: 'わる',
    meaning: 'Làm vỡ',
    furigana: '割(わ)る',
    visualClue: 'Đập vỡ con lợn đất tiết kiệm.',
    soundMnemonic: 'Wa rự.',
    wackyStory: 'Làm vỡ cái ly.',
    kanjiDeconstruction: ['割 (CÁT: chia, vỡ)'],
    logicalAnchor: 'Làm cho một vật bị vỡ ra.',
    collocation: '貯金箱を割る (Đập hộp tiết kiệm/lợn đất)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-69',
    word: '言葉遣い',
    reading: 'ことばづかい',
    meaning: 'Cách dùng từ',
    furigana: '言(こと)葉(ば)遣(づか)い',
    visualClue: 'Một người đang nói chuyện rất lịch sự.',
    soundMnemonic: 'Ko to ba zu kai.',
    wackyStory: 'Sử dụng từ ngữ một cách khéo léo.',
    kanjiDeconstruction: ['言 (NGÔN: lời nói)', '葉 (DIỆP: lá, ngôn từ)', '遣 (KHIỂN: sử dụng)'],
    logicalAnchor: 'Cách thức sử dụng ngôn từ.',
    collocation: '丁寧な言葉遣い (Cách dùng từ lịch sự)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-70',
    word: '間違う',
    reading: 'まちがう',
    meaning: 'Nhầm lẫn',
    furigana: '間(ま)違(ちが)う',
    visualClue: 'Gạch chéo đỏ đánh dấu một câu trả lời sai.',
    soundMnemonic: 'Ma chi ga ư.',
    wackyStory: 'Mắc một lỗi sai.',
    kanjiDeconstruction: ['間 (GIAN: khoảng trống)', '違 (VI: sai, khác)'],
    logicalAnchor: 'Tạo ra sự sai khác.',
    collocation: '道を間違う (Nhầm đường)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-71',
    word: 'ショック',
    reading: 'しょっく',
    meaning: 'Sốc',
    furigana: 'ショック',
    visualClue: 'Một người đứng sững lại vì một tin tức bất ngờ.',
    soundMnemonic: 'Shốc cự.',
    wackyStory: 'Nhận một cú sốc lớn.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Shock.',
    collocation: 'ショックを受ける (Bị sốc)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-72',
    word: '受ける',
    reading: 'うける',
    meaning: 'Bị / Nhận (bị sốc)',
    furigana: '受(う)ける',
    visualClue: 'Nhận một tác động từ bên ngoài.',
    soundMnemonic: 'Ư kê rự.',
    wackyStory: 'Chịu nhận một cú đánh.',
    kanjiDeconstruction: ['受 (THỤ: nhận)'],
    logicalAnchor: 'Tiếp nhận hoặc chịu đựng điều gì đó.',
    collocation: 'ショックを受ける (Bị sốc)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-73',
    word: '落ち込む',
    reading: 'おちこむ',
    meaning: 'Buồn bã / Suy sụp',
    furigana: '落(お)ち込(こ)む',
    visualClue: 'Một người đang ngồi thu lu, cúi gầm mặt xuống đất.',
    soundMnemonic: 'O chi ko mự.',
    wackyStory: 'Rơi vào trạng thái suy sụp.',
    kanjiDeconstruction: ['落 (LẠC: rơi)', '込 (VÀO: vào)'],
    logicalAnchor: 'Tâm trạng bị kéo xuống thấp.',
    collocation: '試験に落ちて落ち込む (Thi trượt nên buồn bã)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-74',
    word: 'わざわざ',
    reading: 'わざわざ',
    meaning: 'Riêng để / Đặc biệt',
    furigana: 'わざわざ',
    visualClue: 'Một người cất công lặn lội đường xa để đến thăm bạn.',
    soundMnemonic: 'Wa za wa za.',
    wackyStory: 'Cất công làm việc gì đó.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Dành công sức đặc biệt cho một việc không nhất thiết phải làm.',
    collocation: 'わざわざ来てくれてありがとう (Cảm ơn bạn đã cất công đến đây)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-75',
    word: '倒す',
    reading: 'たおす',
    meaning: 'Đánh đổ / Làm đổ',
    furigana: '倒(たお)す',
    visualClue: 'Vô tình chạm tay làm đổ cốc nước.',
    soundMnemonic: 'Ta ô sư.',
    wackyStory: 'Làm ngã một đồ vật.',
    kanjiDeconstruction: ['倒 (ĐẢO: đổ, ngã)'],
    logicalAnchor: 'Làm cho một vật đang đứng thẳng bị ngã xuống.',
    collocation: '花瓶を倒す (Làm đổ bình hoa)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-76',
    word: '汚す',
    reading: 'よごす',
    meaning: 'Làm bẩn',
    furigana: '汚(よご)す',
    visualClue: 'Áo trắng bị dính cà phê.',
    soundMnemonic: 'Yo gô sư.',
    wackyStory: 'Làm dơ cái áo.',
    kanjiDeconstruction: ['汚 (Ô: bẩn)'],
    logicalAnchor: 'Gây ra vết bẩn trên bề mặt.',
    collocation: '服を汚す (Làm bẩn quần áo)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-77',
    word: '本気な',
    reading: 'ほんきな',
    meaning: 'Thực lòng / Nghiêm túc',
    furigana: '本(ほん)気(き)な',
    visualClue: 'Ánh mắt kiên định của một người khi nói ra quyết định của mình.',
    soundMnemonic: 'Hon ki.',
    wackyStory: 'Làm bằng cả tấm lòng.',
    kanjiDeconstruction: ['本 (BẢN: gốc, thật)', '気 (KHÍ: tâm trí)'],
    logicalAnchor: 'Tâm trí đặt vào một cách chân thực.',
    collocation: '本気で怒る (Giận thực sự)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-78',
    word: 'わざと',
    reading: 'わざと',
    meaning: 'Cố tình',
    furigana: 'わざと',
    visualClue: 'Một đứa trẻ cố tình ném đồ chơi đi.',
    soundMnemonic: 'Wa za tô.',
    wackyStory: 'Cố tình gây chú ý.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Hành động có chủ ý rõ ràng.',
    collocation: 'わざと負ける (Cố tình thua)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-79',
    word: '後悔する',
    reading: 'こうかいする',
    meaning: 'Hối hận',
    furigana: '後(こう)悔(かい)する',
    visualClue: 'Người ôm đầu tiếc nuối vì một quyết định sai lầm.',
    soundMnemonic: 'Ko kai.',
    wackyStory: 'Hối tiếc về quá khứ.',
    kanjiDeconstruction: ['後 (HẬU: sau)', '悔 (HỐI: hối hận)'],
    logicalAnchor: 'Cảm giác hối tiếc sau khi sự việc đã xảy ra.',
    collocation: '後悔先に立たず (Hối hận thì cũng muộn rồi)',
    lessonId: 'lesson-8'
  },
  {
    id: 'vocab-8-80',
    word: 'なんで',
    reading: 'なんで',
    meaning: 'Vì sao / Tại sao',
    furigana: 'なんで',
    visualClue: 'Khuôn mặt đầy thắc mắc với dấu chấm hỏi.',
    soundMnemonic: 'Nan đê.',
    wackyStory: 'Tại sao lại như vậy?',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ hỏi lý do (bằng với どうして nhưng suồng sã hơn).',
    collocation: 'なんで泣いているの (Tại sao bạn lại khóc)',
    lessonId: 'lesson-8'
  }
];
