import { Vocabulary } from './types';

export const lesson9Words: Vocabulary[] = [
  {
    id: 'vocab-9-1',
    word: 'なんか',
    reading: 'なんか',
    meaning: 'Có gì đó',
    furigana: 'なんか',
    visualClue: 'Một người đang có linh cảm lạ.',
    soundMnemonic: 'Nang ka.',
    wackyStory: 'Có gì đó đang xảy ra.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Cảm giác có điều gì đó.',
    collocation: 'なんか変だ (Có gì đó lạ lạ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-2',
    word: '変な',
    reading: 'へんな',
    meaning: 'Lạ / kì lạ',
    furigana: '変(へん)な',
    visualClue: 'Một sinh vật có hình thù kỳ dị.',
    soundMnemonic: 'Hên na.',
    wackyStory: 'Một sự việc rất hên nhưng cũng rất kỳ lạ.',
    kanjiDeconstruction: ['変 (BIẾN: thay đổi, kỳ lạ)'],
    logicalAnchor: 'Khác thường, không giống bình thường.',
    collocation: '変な音がする (Có âm thanh lạ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-3',
    word: 'ふもと',
    reading: 'ふもと',
    meaning: 'Chân núi',
    furigana: 'ふもと',
    visualClue: 'Ngôi làng nhỏ nằm ở dưới chân một ngọn núi lớn.',
    soundMnemonic: 'Phư mô tô.',
    wackyStory: 'Dưới chân núi có một chiếc xe mô tô.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Phần thấp nhất của ngọn núi.',
    collocation: '山のふもと (Chân núi)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-4',
    word: '～軒',
    reading: '～けん',
    meaning: '～ngôi (Đếm nhà cửa, cửa hàng)',
    furigana: '～軒(けん)',
    visualClue: 'Một dãy nhà nằm sát nhau.',
    soundMnemonic: 'Kên.',
    wackyStory: 'Đếm số ngôi nhà.',
    kanjiDeconstruction: ['軒 (HIÊN: mái hiên, đếm nhà)'],
    logicalAnchor: 'Đơn vị đếm nhà hoặc cửa hàng.',
    collocation: '家が１軒ある (Có 1 ngôi nhà)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-5',
    word: 'お参りする',
    reading: 'おまいりする',
    meaning: 'Lễ chùa / Đi viếng đền thờ',
    furigana: 'お参(まい)りする',
    visualClue: 'Người ta đang chắp tay cầu nguyện ở đền thờ.',
    soundMnemonic: 'Ô mai ri.',
    wackyStory: 'Đi chùa cầu may mắn.',
    kanjiDeconstruction: ['参 (THAM: tham gia, đi viếng)'],
    logicalAnchor: 'Đến đền chùa để cầu nguyện.',
    collocation: '神社にお参りする (Đi lễ đền)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-6',
    word: '村人',
    reading: 'むらびと',
    meaning: 'Dân làng',
    furigana: '村(むら)人(びと)',
    visualClue: 'Những người nông dân sống trong làng.',
    soundMnemonic: 'Mư ra bi tô.',
    wackyStory: 'Người dân trong làng tụ tập.',
    kanjiDeconstruction: ['村 (THÔN: làng)', '人 (NHÂN: người)'],
    logicalAnchor: 'Người sống ở một ngôi làng.',
    collocation: '村人が集まる (Dân làng tụ tập)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-7',
    word: '平気な',
    reading: 'へいきな',
    meaning: 'Bình tĩnh / dửng dưng',
    furigana: '平(へい)気(き)な',
    visualClue: 'Một người đứng thản nhiên dù xung quanh đang rất ồn ào.',
    soundMnemonic: 'Hê ki.',
    wackyStory: 'Dửng dưng không quan tâm.',
    kanjiDeconstruction: ['平 (BÌNH: bằng phẳng)', '気 (KHÍ: tâm trạng)'],
    logicalAnchor: 'Tâm trạng bình tĩnh, không dao động.',
    collocation: '平気な顔をする (Làm vẻ mặt dửng dưng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-8',
    word: '和尚',
    reading: 'おしょう',
    meaning: 'Hòa thượng',
    furigana: '和(お)尚(しょう)',
    visualClue: 'Nhà sư đang mặc áo cà sa.',
    soundMnemonic: 'Ô shô.',
    wackyStory: 'Hòa thượng đang tụng kinh.',
    kanjiDeconstruction: ['和 (HÒA: hòa bình)', '尚 (THƯỢNG: tôn trọng)'],
    logicalAnchor: 'Chức sắc trong Phật giáo.',
    collocation: '和尚さん (Vị hòa thượng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-9',
    word: 'わいわい',
    reading: 'わいわい',
    meaning: 'Ồn ào / náo động lên',
    furigana: 'わいわい',
    visualClue: 'Một đám đông đang la hét vui vẻ.',
    soundMnemonic: 'Wai wai.',
    wackyStory: 'Đám đông ồn ào.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ tượng thanh diễn tả sự ồn ào.',
    collocation: 'わいわい騒ぐ (Làm ồn ào náo động)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-10',
    word: 'やって来る',
    reading: 'やってくる',
    meaning: 'Đến',
    furigana: 'やって来(く)る',
    visualClue: 'Một chiếc tàu hỏa đang tiến vào sân ga.',
    soundMnemonic: 'Yát tê kư rự.',
    wackyStory: 'Một người nào đó tiến tới.',
    kanjiDeconstruction: ['来 (LAI: đến)'],
    logicalAnchor: 'Từ xa tiến lại gần.',
    collocation: '春がやって来る (Mùa xuân đến)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-11',
    word: '口々に',
    reading: 'くちぐちに',
    meaning: 'Ồn ào lộn xộn (Mỗi người một câu)',
    furigana: '口々(くちぐち)に',
    visualClue: 'Mọi người trong phòng họp tranh nhau nói.',
    soundMnemonic: 'Kư chi gư chi ni.',
    wackyStory: 'Mỗi người một cái miệng thi nhau nói.',
    kanjiDeconstruction: ['口 (KHẨU: miệng)'],
    logicalAnchor: 'Mỗi người mở miệng nói ý kiến riêng.',
    collocation: '口々に文句を言う (Mỗi người phàn nàn một câu)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-12',
    word: '裸',
    reading: 'はだか',
    meaning: 'Khỏa thân / trần trụi',
    furigana: '裸(はだか)',
    visualClue: 'Một người cởi trần.',
    soundMnemonic: 'Ha đa ca.',
    wackyStory: 'Da thịt phơi bày.',
    kanjiDeconstruction: ['裸 (LÕA: trần trụi)'],
    logicalAnchor: 'Không mặc quần áo hoặc không có lớp vỏ bọc.',
    collocation: '裸足 (Chân trần)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-13',
    word: '誤解する',
    reading: 'ごかいする',
    meaning: 'Hiểu nhầm',
    furigana: '誤(ご)解(かい)する',
    visualClue: 'Hai người tranh cãi vì hiểu lầm ý nhau.',
    soundMnemonic: 'Gô kai.',
    wackyStory: 'Giải thích sai dẫn đến hiểu lầm.',
    kanjiDeconstruction: ['誤 (NGỘ: nhầm lẫn)', '解 (GIẢI: hiểu, giải quyết)'],
    logicalAnchor: 'Hiểu sai vấn đề.',
    collocation: '言葉を誤解する (Hiểu nhầm lời nói)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-14',
    word: '文章',
    reading: 'ぶんしょう',
    meaning: 'Câu văn / Đoạn văn',
    furigana: '文(ぶん)章(しょう)',
    visualClue: 'Một bài luận dài trên giấy.',
    soundMnemonic: 'Bưn shô.',
    wackyStory: 'Viết một câu văn.',
    kanjiDeconstruction: ['文 (VĂN: câu văn)', '章 (CHƯƠNG: chương mục)'],
    logicalAnchor: 'Một đoạn văn bản.',
    collocation: '文章を書く (Viết một đoạn văn)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-15',
    word: '笑い出す',
    reading: 'わらいだす',
    meaning: 'Cười phá lên',
    furigana: '笑(わら)い出(だ)す',
    visualClue: 'Một người đột nhiên ôm bụng cười lớn.',
    soundMnemonic: 'Wa rai đa sư.',
    wackyStory: 'Bật cười không kiểm soát được.',
    kanjiDeconstruction: ['笑 (TIẾU: cười)', '出 (XUẤT: ra)'],
    logicalAnchor: 'Tiếng cười đột ngột phát ra.',
    collocation: '急に笑い出す (Đột nhiên cười phá lên)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-16',
    word: '訳',
    reading: 'わけ',
    meaning: 'Lý do / Nguyên nhân',
    furigana: '訳(わけ)',
    visualClue: 'Dấu chấm hỏi khi ai đó tìm lý do cho một hành động.',
    soundMnemonic: 'Wa kê.',
    wackyStory: 'Đưa ra một lý do.',
    kanjiDeconstruction: ['訳 (DỊCH: dịch, lý do)'],
    logicalAnchor: 'Nguyên do đằng sau sự việc.',
    collocation: '遅れた訳 (Lý do đến trễ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-17',
    word: '早口言葉',
    reading: 'はやくちことば',
    meaning: 'Từ nói nhanh mồm (Câu nói líu lưỡi)',
    furigana: '早(はや)口(くち)言(こと)葉(ば)',
    visualClue: 'Một người cố gắng nói một câu uốn lưỡi thật nhanh.',
    soundMnemonic: 'Ha ya kư chi cô tô ba.',
    wackyStory: 'Nói những câu líu lưỡi thật nhanh.',
    kanjiDeconstruction: ['早 (TẢO: nhanh)', '口 (KHẨU: miệng)', '言 (NGÔN: lời)', '葉 (DIỆP: từ ngữ)'],
    logicalAnchor: 'Những câu dùng để tập nói nhanh.',
    collocation: '早口言葉を言う (Nói một câu líu lưỡi)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-18',
    word: '柿',
    reading: 'かき',
    meaning: 'Quả hồng',
    furigana: '柿(かき)',
    visualClue: 'Một quả hồng màu cam chín mọng.',
    soundMnemonic: 'Ka ki.',
    wackyStory: 'Cây hồng ra quả.',
    kanjiDeconstruction: ['柿 (THỊ: quả hồng)'],
    logicalAnchor: 'Một loại quả ngọt màu cam.',
    collocation: '柿を食べる (Ăn hồng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-19',
    word: '食う',
    reading: 'くう',
    meaning: 'Ăn / Xơi (Dạng suồng sã)',
    furigana: '食(く)う',
    visualClue: 'Một người đàn ông đang ăn ngấu nghiến.',
    soundMnemonic: 'Kư ư.',
    wackyStory: 'Xơi cơm thôi.',
    kanjiDeconstruction: ['食 (THỰC: ăn)'],
    logicalAnchor: 'Hành động nhai và nuốt thức ăn (dành cho nam giới/động vật).',
    collocation: '飯を食う (Ăn cơm)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-20',
    word: 'パジャマ',
    reading: 'ぱじゃま',
    meaning: 'Quần áo ngủ',
    furigana: 'パジャマ',
    visualClue: 'Bộ quần áo pijama mềm mại dùng để đi ngủ.',
    soundMnemonic: 'Pa ja ma.',
    wackyStory: 'Mặc đồ ngủ đi ngủ.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Pajamas.',
    collocation: 'パジャマを着る (Mặc đồ ngủ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-21',
    word: 'カエル',
    reading: 'かえる',
    meaning: 'Con ếch',
    furigana: 'カエル',
    visualClue: 'Con ếch đang nhảy.',
    soundMnemonic: 'Ka ê rự.',
    wackyStory: 'Con ếch kêu ộp ộp.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Động vật lưỡng cư.',
    collocation: 'カエルが鳴く (Ếch kêu)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-22',
    word: 'ぴょこぴょこ',
    reading: 'ぴょこぴょこ',
    meaning: 'Tiếng ếch kêu / Nhảy tưng tưng',
    furigana: 'ぴょこぴょこ',
    visualClue: 'Con ếch nhảy cẫng lên từng bước nhỏ.',
    soundMnemonic: 'Pyô cô pyô cô.',
    wackyStory: 'Nhảy tưng tưng.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ tượng thanh/tượng hình.',
    collocation: 'カエルがぴょこぴょこ跳ねる (Ếch nhảy tưng tưng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-23',
    word: 'なぞなぞ',
    reading: 'なぞなぞ',
    meaning: 'Điều bí ẩn / Câu đố',
    furigana: 'なぞなぞ',
    visualClue: 'Trò chơi giải câu đố chữ.',
    soundMnemonic: 'Na zô na zô.',
    wackyStory: 'Trả lời câu đố vui.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Câu đố dùng để thử thách trí tuệ.',
    collocation: 'なぞなぞを出す (Đưa ra câu đố)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-24',
    word: '回文',
    reading: 'かいぶん',
    meaning: 'Câu nói ngược (Palindrome)',
    furigana: '回(かい)文(ぶん)',
    visualClue: 'Một câu văn đọc xuôi hay ngược đều giống nhau.',
    soundMnemonic: 'Kai bưn.',
    wackyStory: 'Văn xoay vòng.',
    kanjiDeconstruction: ['回 (HỒI: xoay vòng)', '文 (VĂN: câu)'],
    logicalAnchor: 'Câu văn đọc từ hai chiều giống hệt nhau.',
    collocation: '回文を作る (Tạo ra câu nói ngược)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-25',
    word: 'マウス',
    reading: 'まうす',
    meaning: 'Chuột (Máy tính / Con chuột)',
    furigana: 'マウス',
    visualClue: 'Con chuột máy tính.',
    soundMnemonic: 'Ma ư sư.',
    wackyStory: 'Sử dụng chuột máy tính.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Mouse.',
    collocation: 'パソコンのマウス (Chuột máy tính)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-26',
    word: '崖',
    reading: 'がけ',
    meaning: 'Vách đá',
    furigana: '崖(がけ)',
    visualClue: 'Một vách núi đá dựng đứng sát biển.',
    soundMnemonic: 'Ga kê.',
    wackyStory: 'Leo vách đá.',
    kanjiDeconstruction: ['崖 (NHAI: vách đá)'],
    logicalAnchor: 'Sườn núi hoặc đá dựng đứng.',
    collocation: '崖から落ちる (Rơi xuống từ vách đá)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-27',
    word: '～わ',
    reading: '～わ',
    meaning: 'Biểu hiện cảm thán',
    furigana: '～わ',
    visualClue: 'Một người đưa tay lên miệng thể hiện sự ngạc nhiên.',
    soundMnemonic: 'Wa.',
    wackyStory: 'Chà!',
    kanjiDeconstruction: [],
    logicalAnchor: 'Trợ từ cuối câu.',
    collocation: 'きれいだわ (Đẹp quá nhỉ!)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-28',
    word: '詩',
    reading: 'し',
    meaning: 'Thơ',
    furigana: '詩(し)',
    visualClue: 'Một bài thơ hay trên giấy.',
    soundMnemonic: 'Shi.',
    wackyStory: 'Làm thơ.',
    kanjiDeconstruction: ['詩 (THI: thơ)'],
    logicalAnchor: 'Tác phẩm văn học có vần điệu.',
    collocation: '詩を書く (Làm thơ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-29',
    word: '唄',
    reading: 'うた',
    meaning: 'Bài hát',
    furigana: '唄(うた)',
    visualClue: 'Một người đang ca hát.',
    soundMnemonic: 'Ư ta.',
    wackyStory: 'Hát một bài hát.',
    kanjiDeconstruction: ['唄 (BÁI: bài hát)'],
    logicalAnchor: 'Giai điệu có lời ca.',
    collocation: '唄を歌う (Hát một bài hát)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-30',
    word: '載る',
    reading: 'のる',
    meaning: 'Đưa lên / được đăng',
    furigana: '載(の)る',
    visualClue: 'Bài báo được đăng trên tạp chí.',
    soundMnemonic: 'Nô rự.',
    wackyStory: 'Được đăng lên báo.',
    kanjiDeconstruction: ['載 (TẢI: đăng, chở)'],
    logicalAnchor: 'Được công bố trên các phương tiện truyền thông.',
    collocation: '新聞に載る (Được đăng trên báo)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-31',
    word: '小鳥',
    reading: 'ことり',
    meaning: 'Chim non',
    furigana: '小(こ)鳥(とり)',
    visualClue: 'Chú chim nhỏ đang hót.',
    soundMnemonic: 'Cô tô ri.',
    wackyStory: 'Chú chim non nhảy nhót.',
    kanjiDeconstruction: ['小 (TIỂU: nhỏ)', '鳥 (ĐIỂU: chim)'],
    logicalAnchor: 'Loài chim có kích thước nhỏ.',
    collocation: '小鳥が鳴く (Chim non hót)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-32',
    word: '鈴',
    reading: 'すず',
    meaning: 'Chuông / cái chuông',
    furigana: '鈴(すず)',
    visualClue: 'Một chiếc chuông reo leng keng.',
    soundMnemonic: 'Sư zư.',
    wackyStory: 'Rung chuông.',
    kanjiDeconstruction: ['鈴 (LINH: cái chuông)'],
    logicalAnchor: 'Vật phát ra âm thanh leng keng.',
    collocation: '鈴を鳴らす (Rung chuông)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-33',
    word: '両手',
    reading: 'りょうて',
    meaning: 'Hai tay',
    furigana: '両(りょう)手(て)',
    visualClue: 'Một người đang dang rộng hai tay.',
    soundMnemonic: 'Ryô tê.',
    wackyStory: 'Giơ hai tay lên.',
    kanjiDeconstruction: ['両 (LƯỠNG: hai)', '手 (THỦ: tay)'],
    logicalAnchor: 'Cả hai bàn tay.',
    collocation: '両手を上げる (Giơ hai tay lên)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-34',
    word: '広げる',
    reading: 'ひろげる',
    meaning: 'Mở rộng ra',
    furigana: '広(ひろ)げる',
    visualClue: 'Mở rộng bản đồ ra xem.',
    soundMnemonic: 'Hi rô gê rự.',
    wackyStory: 'Mở rộng không gian.',
    kanjiDeconstruction: ['広 (QUẢNG: rộng)'],
    logicalAnchor: 'Làm cho diện tích hoặc phạm vi lớn hơn.',
    collocation: '地図を広げる (Mở rộng bản đồ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-35',
    word: '空',
    reading: 'そら',
    meaning: 'Bầu trời',
    furigana: '空(そら)',
    visualClue: 'Bầu trời xanh ngắt.',
    soundMnemonic: 'Sô ra.',
    wackyStory: 'Nhìn lên bầu trời.',
    kanjiDeconstruction: ['空 (KHÔNG: bầu trời)'],
    logicalAnchor: 'Khoảng không gian phía trên trái đất.',
    collocation: '空を飛ぶ (Bay trên bầu trời)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-36',
    word: 'ちっとも',
    reading: 'ちっとも',
    meaning: 'Không ... một chút gì',
    furigana: 'ちっとも',
    visualClue: 'Biểu cảm kiên quyết từ chối.',
    soundMnemonic: 'Chít tô mô.',
    wackyStory: 'Không thèm để tâm một chút nào.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Hoàn toàn không (Dùng với câu phủ định).',
    collocation: 'ちっとも面白くない (Hoàn toàn không thú vị)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-37',
    word: '地べた',
    reading: 'ぢべた',
    meaning: 'Mặt đất',
    furigana: '地(ぢ)べた',
    visualClue: 'Một người đang ngồi xổm trên mặt đất.',
    soundMnemonic: 'Ji bê ta.',
    wackyStory: 'Ngồi sát đất.',
    kanjiDeconstruction: ['地 (ĐỊA: đất)'],
    logicalAnchor: 'Bề mặt của mặt đất.',
    collocation: '地べたに座る (Ngồi trên mặt đất)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-38',
    word: 'ゆする',
    reading: 'ゆする',
    meaning: 'Rung / lắc / đu đưa',
    furigana: 'ゆする',
    visualClue: 'Rung nhẹ một cái cây để quả rụng xuống.',
    soundMnemonic: 'Yư sư rự.',
    wackyStory: 'Rung lắc dữ dội.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Làm cho vật gì đó chuyển động qua lại.',
    collocation: '木をゆする (Rung cây)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-39',
    word: '暮らす',
    reading: 'くらす',
    meaning: 'Sống',
    furigana: '暮(く)らす',
    visualClue: 'Một gia đình đang sinh hoạt vui vẻ.',
    soundMnemonic: 'Kư ra sư.',
    wackyStory: 'Sống một cuộc đời bình yên.',
    kanjiDeconstruction: ['暮 (MỘ: chiều tối, sống)'],
    logicalAnchor: 'Trải qua cuộc sống hàng ngày.',
    collocation: '平和に暮らす (Sống hòa bình)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-40',
    word: '～後',
    reading: '～ご',
    meaning: 'Sau khi～ (Ví dụ: 帰国後 - sau khi về nước)',
    furigana: '～後(ご)',
    visualClue: 'Mũi tên chỉ về phía trước báo hiệu sự việc xảy ra sau đó.',
    soundMnemonic: 'Gô.',
    wackyStory: 'Sau khi mọi chuyện kết thúc.',
    kanjiDeconstruction: ['後 (HẬU: sau)'],
    logicalAnchor: 'Chỉ thời điểm tiếp theo một hành động.',
    collocation: '帰国後 (Sau khi về nước)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-41',
    word: '励ます',
    reading: 'はげます',
    meaning: 'Động viên / khích lệ',
    furigana: '励(はげ)ます',
    visualClue: 'Một người đang cổ vũ, vỗ vai khích lệ người khác.',
    soundMnemonic: 'Ha gê ma sư.',
    wackyStory: 'Khích lệ tinh thần làm việc.',
    kanjiDeconstruction: ['励 (LỆ: khích lệ)'],
    logicalAnchor: 'Cổ vũ để người khác có thêm động lực.',
    collocation: '友だちを励ます (Động viên bạn bè)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-42',
    word: '生きる',
    reading: 'いきる',
    meaning: 'Sống',
    furigana: '生(い)きる',
    visualClue: 'Một mầm non đang vươn lên từ mặt đất.',
    soundMnemonic: 'I ki rự.',
    wackyStory: 'Tồn tại và phát triển.',
    kanjiDeconstruction: ['生 (SINH: sống)'],
    logicalAnchor: 'Trạng thái đang tồn tại.',
    collocation: '長く生きる (Sống lâu)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-43',
    word: '時代',
    reading: 'じだい',
    meaning: 'Thời đại / thời thế',
    furigana: '時(じ)代(だい)',
    visualClue: 'Hình ảnh chuyển giao từ quá khứ đến hiện đại.',
    soundMnemonic: 'Ji đai.',
    wackyStory: 'Thời đại của công nghệ.',
    kanjiDeconstruction: ['時 (THỜI: thời gian)', '代 (ĐẠI: thời đại)'],
    logicalAnchor: 'Một khoảng thời gian dài trong lịch sử.',
    collocation: '新しい時代 (Thời đại mới)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-44',
    word: '個性',
    reading: 'こせい',
    meaning: 'Cá tính',
    furigana: '個(こ)性(せい)',
    visualClue: 'Một người mặc đồ nổi bật trong đám đông.',
    soundMnemonic: 'Cô sê.',
    wackyStory: 'Thể hiện cá tính riêng.',
    kanjiDeconstruction: ['個 (CÁ: cá nhân)', '性 (TÍNH: tính cách)'],
    logicalAnchor: 'Đặc điểm riêng biệt của mỗi người.',
    collocation: '個性を伸ばす (Phát huy cá tính)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-45',
    word: '～らしさ',
    reading: '～らしさ',
    meaning: 'Vẻ～ (Ví dụ: 自分らしさ - vẻ riêng)',
    furigana: '～らしさ',
    visualClue: 'Người thể hiện phong cách tự nhiên của bản thân.',
    soundMnemonic: 'Ra shi sa.',
    wackyStory: 'Giữ đúng bản sắc của mình.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Thể hiện bản chất đặc trưng của ai đó.',
    collocation: '自分らしさを大切にする (Trân trọng sự khác biệt của bản thân)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-46',
    word: '認める',
    reading: 'みとめる',
    meaning: 'Nhận / thừa nhận',
    furigana: '認(みと)める',
    visualClue: 'Một người gật đầu đồng ý với ý kiến của người khác.',
    soundMnemonic: 'Mi tô mê rự.',
    wackyStory: 'Thừa nhận sai lầm.',
    kanjiDeconstruction: ['認 (NHẬN: công nhận)'],
    logicalAnchor: 'Chấp nhận sự thật hoặc sự tồn tại của điều gì đó.',
    collocation: '自分の間違いを認める (Thừa nhận sai lầm của bản thân)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-47',
    word: '込める',
    reading: 'こめる',
    meaning: 'Nạp / bỏ vào / Dồn (tình cảm)',
    furigana: '込(こ)める',
    visualClue: 'Đặt món quà nhỏ kèm theo bức thư tình cảm.',
    soundMnemonic: 'Cô mê rự.',
    wackyStory: 'Dồn hết tình cảm vào món quà.',
    kanjiDeconstruction: ['込 (VÀO: nạp vào, chứa)'],
    logicalAnchor: 'Đưa cái gì đó (như tình cảm, sức lực) vào trong.',
    collocation: '心を込める (Dành trọn tấm lòng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-48',
    word: '許す',
    reading: 'ゆるす',
    meaning: 'Tha thứ / bỏ qua / cho phép',
    furigana: '許(ゆる)す',
    visualClue: 'Một người mỉm cười xoa đầu người vừa làm sai.',
    soundMnemonic: 'Yư rư sư.',
    wackyStory: 'Tha lỗi cho hành động sai trái.',
    kanjiDeconstruction: ['許 (HỨA: tha thứ)'],
    logicalAnchor: 'Chấp nhận tha thứ hoặc cho phép.',
    collocation: '罪を許す (Tha thứ tội lỗi)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-49',
    word: '消費する',
    reading: 'しょうひする',
    meaning: 'Tiêu phí / tiêu dùng',
    furigana: '消(しょう)費(ひ)する',
    visualClue: 'Hành động mua sắm hàng hóa.',
    soundMnemonic: 'Shô hi sư rự.',
    wackyStory: 'Sử dụng tiền bạc và thời gian.',
    kanjiDeconstruction: ['消 (TIÊU: tiêu diệt, biến mất)', '費 (PHÍ: tiêu xài)'],
    logicalAnchor: 'Sử dụng hàng hóa hoặc năng lượng.',
    collocation: 'エネルギーを消費する (Tiêu thụ năng lượng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-50',
    word: '～者',
    reading: '～しゃ',
    meaning: 'Người～ (Ví dụ: 消費者 - người tiêu dùng)',
    furigana: '～者(しゃ)',
    visualClue: 'Hình bóng một người nào đó đang mua hàng.',
    soundMnemonic: 'Sha.',
    wackyStory: 'Chỉ người tham gia một hoạt động.',
    kanjiDeconstruction: ['者 (GIẢ: người)'],
    logicalAnchor: 'Hậu tố chỉ người làm việc gì đó.',
    collocation: '消費者 (Người tiêu dùng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-51',
    word: '開発する',
    reading: 'かいはつする',
    meaning: 'Khai thác / phát triển',
    furigana: '開(かい)発(はつ)する',
    visualClue: 'Công trình xây dựng một khu công nghệ mới.',
    soundMnemonic: 'Kai ha tsu sư rự.',
    wackyStory: 'Phát triển vùng đất hoang.',
    kanjiDeconstruction: ['開 (KHAI: mở)', '発 (PHÁT: phát sinh)'],
    logicalAnchor: 'Nghiên cứu tạo ra hoặc mở mang điều gì đó.',
    collocation: '新しい技術を開発する (Phát triển kỹ thuật mới)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-52',
    word: '実話',
    reading: 'じつわ',
    meaning: 'Chuyện thật',
    furigana: '実(じつ)話(わ)',
    visualClue: 'Một cuốn sách ghi chép lại các sự kiện có thật.',
    soundMnemonic: 'Ji tsu wa.',
    wackyStory: 'Kể lại một câu chuyện thực tế.',
    kanjiDeconstruction: ['実 (THỰC: sự thật)', '話 (THOẠI: câu chuyện)'],
    logicalAnchor: 'Câu chuyện dựa trên sự việc đã diễn ra.',
    collocation: '実話を元にした映画 (Phim dựa trên câu chuyện có thật)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-53',
    word: 'コマーシャル',
    reading: 'こまーしゃる',
    meaning: 'Quảng cáo',
    furigana: 'コマーシャル',
    visualClue: 'Một đoạn quảng cáo trên TV.',
    soundMnemonic: 'Cô ma shô.',
    wackyStory: 'Quảng cáo thương mại.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Commercial.',
    collocation: 'テレビのコマーシャル (Quảng cáo truyền hình)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-54',
    word: 'フリーダイヤル',
    reading: 'ふりーだいやる',
    meaning: 'Dịch vụ điện thoại miễn phí (tổng đài miễn phí)',
    furigana: 'フリーダイヤル',
    visualClue: 'Một số điện thoại có đầu số 0120.',
    soundMnemonic: 'Phư ri đai ya rự.',
    wackyStory: 'Gọi điện không tốn tiền.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn: Free dial.',
    collocation: 'フリーダイヤルに電話する (Gọi đến tổng đài miễn phí)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-55',
    word: '～製',
    reading: '～せい',
    meaning: 'Sản phẩm bằng～ (Ví dụ: 革製 - Sản phẩm bằng da)',
    furigana: '～製(せい)',
    visualClue: 'Một chiếc túi có nhãn ghi làm từ da thật.',
    soundMnemonic: 'Sê.',
    wackyStory: 'Đồ được làm ra.',
    kanjiDeconstruction: ['製 (CHẾ: chế tạo)'],
    logicalAnchor: 'Sản xuất, làm từ chất liệu nào đó.',
    collocation: '革製のバッグ (Túi bằng da)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-56',
    word: 'かけ間違い',
    reading: 'かけまちがい',
    meaning: 'Gọi nhầm',
    furigana: 'かけ間(ま)違(ちが)い',
    visualClue: 'Bấm nhầm số và người lạ nhấc máy.',
    soundMnemonic: 'Ka kê ma chi gai.',
    wackyStory: 'Gọi nhầm số điện thoại.',
    kanjiDeconstruction: ['間 (GIAN)', '違 (VI: sai)'],
    logicalAnchor: 'Thực hiện cuộc gọi bị sai số.',
    collocation: '電話のかけ間違い (Sự gọi nhầm điện thoại)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-57',
    word: 'いったい',
    reading: 'いったい',
    meaning: 'Thế nào / Rốt cuộc là',
    furigana: 'いったい',
    visualClue: 'Biểu cảm hoang mang muốn biết chân tướng.',
    soundMnemonic: 'Ít tai.',
    wackyStory: 'Rốt cuộc là sao?',
    kanjiDeconstruction: [],
    logicalAnchor: 'Thường đi với từ để hỏi, mang ý nghĩa nhấn mạnh.',
    collocation: 'いったい何があったの (Rốt cuộc là có chuyện gì vậy?)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-58',
    word: '文字',
    reading: 'もじ',
    meaning: 'Chữ cái / văn tự',
    furigana: '文(も)字(じ)',
    visualClue: 'Các chữ cái A, B, C hoặc Kanji.',
    soundMnemonic: 'Mô ji.',
    wackyStory: 'Đọc chữ.',
    kanjiDeconstruction: ['文 (VĂN: chữ)', '字 (TỰ: chữ)'],
    logicalAnchor: 'Các ký tự dùng để viết.',
    collocation: '文字を書く (Viết chữ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-59',
    word: 'イメージする',
    reading: 'いめーじする',
    meaning: 'Tưởng tượng',
    furigana: 'イメージする',
    visualClue: 'Bong bóng suy nghĩ hiện ra hình ảnh một bãi biển.',
    soundMnemonic: 'I mê ji sư rự.',
    wackyStory: 'Hình dung trong đầu.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ mượn tiếng Anh: Image.',
    collocation: '将来をイメージする (Tưởng tượng về tương lai)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-60',
    word: '数える',
    reading: 'かぞえる',
    meaning: 'Đếm',
    furigana: '数(かぞ)える',
    visualClue: 'Đếm ngón tay từ 1 đến 10.',
    soundMnemonic: 'Ka zô ê rự.',
    wackyStory: 'Đếm số lượng.',
    kanjiDeconstruction: ['数 (SỐ: số lượng)'],
    logicalAnchor: 'Hành động xác định số lượng.',
    collocation: '数を数える (Đếm số)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-61',
    word: '遠足',
    reading: 'えんそく',
    meaning: 'Tham quan / Dã ngoại',
    furigana: '遠(えん)足(そく)',
    visualClue: 'Học sinh tiểu học đeo balo đi chơi công viên.',
    soundMnemonic: 'En sô cự.',
    wackyStory: 'Chuyến đi bộ đường dài.',
    kanjiDeconstruction: ['遠 (VIỄN: xa)', '足 (TÚC: chân)'],
    logicalAnchor: 'Đi bộ một quãng đường xa để ngắm cảnh.',
    collocation: '遠足に行く (Đi dã ngoại)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-62',
    word: '作家',
    reading: 'さっか',
    meaning: 'Tác giả',
    furigana: '作(さっ)家(か)',
    visualClue: 'Người đang ngồi gõ máy chữ hoặc viết tiểu thuyết.',
    soundMnemonic: 'Sắc ca.',
    wackyStory: 'Nhà văn đang sáng tác.',
    kanjiDeconstruction: ['作 (TÁC: sáng tác)', '家 (GIA: người chuyên môn)'],
    logicalAnchor: 'Người làm nghề sáng tác văn học, nghệ thuật.',
    collocation: '有名な作家 (Tác giả nổi tiếng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-63',
    word: '４こま漫画',
    reading: 'よんこままんが',
    meaning: 'Truyện tranh 4 khung cảnh',
    furigana: '４(よん)こま漫(まん)画(が)',
    visualClue: 'Một mẩu truyện tranh ngắn gồm 4 ô vuông.',
    soundMnemonic: 'Yôn cô ma man ga.',
    wackyStory: 'Đọc mẩu truyện tranh hài.',
    kanjiDeconstruction: ['漫 (MẠN: tùy ý)', '画 (HỌA: tranh)'],
    logicalAnchor: 'Truyện tranh ngắn kể câu chuyện trong 4 ô.',
    collocation: '４こま漫画を読む (Đọc truyện tranh 4 khung)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-64',
    word: 'せりふ',
    reading: 'せりふ',
    meaning: 'Lời thoại',
    furigana: 'せりふ',
    visualClue: 'Dòng chữ trong bong bóng thoại của nhân vật truyện tranh.',
    soundMnemonic: 'Sê ri phư.',
    wackyStory: 'Nhân vật nói lời thoại.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Câu nói của nhân vật trong kịch, phim, truyện.',
    collocation: 'せりふを覚える (Nhớ lời thoại)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-65',
    word: '登場人物',
    reading: 'とうじょうじんぶつ',
    meaning: 'Nhân vật xuất hiện (trong truyện, phim)',
    furigana: '登(とう)場(じょう)人(じん)物(ぶつ)',
    visualClue: 'Danh sách các diễn viên trong một bộ phim.',
    soundMnemonic: 'Tô jô jin bư tsu.',
    wackyStory: 'Nhân vật chính bước ra sân khấu.',
    kanjiDeconstruction: ['登 (ĐĂNG: lên)', '場 (TRƯỜNG: nơi)', '人 (NHÂN)', '物 (VẬT)'],
    logicalAnchor: 'Người xuất hiện tại một địa điểm (sân khấu, bối cảnh).',
    collocation: '物語の登場人物 (Nhân vật trong câu chuyện)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-66',
    word: 'はしご',
    reading: 'はしご',
    meaning: 'Cầu thang / cái thang',
    furigana: 'はしご',
    visualClue: 'Cái thang dựa vào tường để leo lên mái nhà.',
    soundMnemonic: 'Ha shi gô.',
    wackyStory: 'Leo lên thang.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Dụng cụ dùng để leo trèo.',
    collocation: 'はしごを登る (Leo thang)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-67',
    word: 'わくわく',
    reading: 'わくわく',
    meaning: 'Hồi hộp vì vui (Vui sướng, háo hức)',
    furigana: 'わくわく',
    visualClue: 'Một đứa trẻ cầm vé đi công viên giải trí.',
    soundMnemonic: 'Wa kư wa kư.',
    wackyStory: 'Tim đập thình thịch vì vui sướng.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ tượng thanh/tượng hình thể hiện sự háo hức.',
    collocation: 'わくわくしながら待つ (Há hức chờ đợi)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-68',
    word: 'はらはら',
    reading: 'はらはら',
    meaning: 'Áy náy / lo lắng / thấp thỏm',
    furigana: 'はらはら',
    visualClue: 'Người xem đang xem xiếc nhào lộn trên dây.',
    soundMnemonic: 'Ha ra ha ra.',
    wackyStory: 'Lo sợ rớt tim.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ tượng thanh/tượng hình thể hiện sự lo âu, thấp thỏm.',
    collocation: 'はらはらして見る (Xem trong sự thấp thỏm)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-69',
    word: 'しょんぼり',
    reading: 'しょんぼり',
    meaning: 'Thẫn thờ / đờ đẫn / ủ rũ',
    furigana: 'しょんぼり',
    visualClue: 'Một người cúi gầm mặt bước đi dưới mưa.',
    soundMnemonic: 'Shôn bô ri.',
    wackyStory: 'Buồn bã ủ rũ vì điểm kém.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ tượng thanh/tượng hình thể hiện sự chán nản, thất vọng.',
    collocation: 'しょんぼりして帰る (Ủ rũ đi về)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-70',
    word: '駄目な',
    reading: 'だめな',
    meaning: 'Không tốt / không thể / vô ích',
    furigana: '駄(だ)目(め)な',
    visualClue: 'Hành động khoát hai tay hình chữ X.',
    soundMnemonic: 'Đa mê.',
    wackyStory: 'Chuyện này không được rồi.',
    kanjiDeconstruction: ['駄 (ĐÀ: thồ hàng)', '目 (MỤC: mắt)'],
    logicalAnchor: 'Không mang lại kết quả tốt.',
    collocation: '駄目な人間 (Người vô dụng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-71',
    word: 'だって',
    reading: 'だって',
    meaning: 'Vì / chả là',
    furigana: 'だって',
    visualClue: 'Một đứa trẻ đang bĩu môi giải thích lý do phạm lỗi.',
    soundMnemonic: 'Đát tê.',
    wackyStory: 'Tại vì... nên...',
    kanjiDeconstruction: [],
    logicalAnchor: 'Liên từ dùng để đưa ra lý do, thường dùng trong hội thoại suồng sã.',
    collocation: 'だって、仕方がない (Bởi vì không còn cách nào khác)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-82',
    word: '顔が広い',
    reading: 'かおがひろい',
    meaning: 'Quen biết rộng',
    furigana: '顔(かお)が広(ひろ)い',
    visualClue: 'Một người có nhiều mối quan hệ xã hội.',
    soundMnemonic: 'Ka ô ga hi rô i.',
    wackyStory: 'Khuôn mặt rộng rãi.',
    kanjiDeconstruction: ['顔 (NHAN: mặt)', '広 (QUẢNG: rộng)'],
    logicalAnchor: 'Quen biết nhiều người.',
    collocation: '顔が広い人 (Người quen biết rộng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-83',
    word: '顔から火が出る',
    reading: 'かおからひがでる',
    meaning: 'Xấu hổ, ngượng',
    furigana: '顔(かお)から火(ひ)が出(で)る',
    visualClue: 'Mặt đỏ bừng vì xấu hổ.',
    soundMnemonic: 'Ka ô ca ra hi ga đê rự.',
    wackyStory: 'Lửa bốc ra từ mặt.',
    kanjiDeconstruction: ['顔 (NHAN: mặt)', '火 (HỎA: lửa)', '出 (XUẤT: ra)'],
    logicalAnchor: 'Đỏ mặt vì ngượng.',
    collocation: '顔から火が出るほど恥ずかしい (Xấu hổ đỏ bừng mặt)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-84',
    word: 'ほっぺた',
    reading: 'ほっぺた',
    meaning: 'Má',
    furigana: 'ほっぺた',
    visualClue: 'Đôi má phúng phính.',
    soundMnemonic: 'Hốp pê ta.',
    wackyStory: 'Hai bên má.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Phần trên khuôn mặt.',
    collocation: 'ほっぺたが落ちる (Ngon rụng má)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-85',
    word: '勘違いする',
    reading: 'かんちがいする',
    meaning: 'Hiểu nhầm',
    furigana: '勘(かん)違(ちが)いする',
    visualClue: 'Một người gãi đầu vì nhận ra mình nhầm.',
    soundMnemonic: 'Kan chi gai.',
    wackyStory: 'Hiểu sai vấn đề.',
    kanjiDeconstruction: ['勘 (KHÁM: trực giác)', '違 (VI: sai)'],
    logicalAnchor: 'Nhận thức sai về một điều gì đó.',
    collocation: '勘違いをしてしまった (Tôi đã hiểu nhầm mất rồi)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-86',
    word: '表現する',
    reading: 'ひょうげんする',
    meaning: 'Biểu hiện, diễn tả',
    furigana: '表(ひょう)現(げん)する',
    visualClue: 'Một nghệ sĩ đang diễn đạt cảm xúc.',
    soundMnemonic: 'Hyô gen.',
    wackyStory: 'Thể hiện ra bên ngoài.',
    kanjiDeconstruction: ['表 (BIỂU: bề ngoài)', '現 (HIỆN: xuất hiện)'],
    logicalAnchor: 'Làm cho người khác hiểu được suy nghĩ, cảm xúc.',
    collocation: '感情を表現する (Biểu hiện cảm xúc)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-87',
    word: '黙る',
    reading: 'だまる',
    meaning: 'Im lặng',
    furigana: '黙(だま)る',
    visualClue: 'Đưa ngón tay trỏ lên môi.',
    soundMnemonic: 'Đa ma rự.',
    wackyStory: 'Giữ im lặng.',
    kanjiDeconstruction: ['黙 (MẶC: im lặng)'],
    logicalAnchor: 'Không nói gì.',
    collocation: '黙って聞いてください (Hãy im lặng và lắng nghe)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-88',
    word: '優勝する',
    reading: 'ゆうしょうする',
    meaning: 'Vô địch',
    furigana: '優(ゆう)勝(しょう)する',
    visualClue: 'Một người nâng cao chiếc cúp vô địch.',
    soundMnemonic: 'Yuu shô.',
    wackyStory: 'Chiến thắng giải đấu.',
    kanjiDeconstruction: ['優 (ƯU: xuất sắc)', '勝 (THẮNG: chiến thắng)'],
    logicalAnchor: 'Đạt được vị trí cao nhất.',
    collocation: '大会で優勝する (Vô địch trong đại hội)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-89',
    word: '飛び上がる',
    reading: 'とびあがる',
    meaning: 'Nhảy lên, bay lên',
    furigana: '飛(と)び上(あ)がる',
    visualClue: 'Một người vui sướng nhảy cẫng lên.',
    soundMnemonic: 'Tô bi a ga rự.',
    wackyStory: 'Bay vút lên không trung.',
    kanjiDeconstruction: ['飛 (PHI: bay)', '上 (THƯỢNG: trên)'],
    logicalAnchor: 'Chuyển động đột ngột lên phía trên.',
    collocation: '嬉しくて飛び上がる (Vui sướng nhảy cẫng lên)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-90',
    word: '飛び出す',
    reading: 'とびだす',
    meaning: 'Đột nhiên xuất hiện, lao ra',
    furigana: '飛(と)び出(だ)す',
    visualClue: 'Một đứa trẻ đột ngột chạy ra đường.',
    soundMnemonic: 'Tô bi đa sư.',
    wackyStory: 'Lao ra ngoài đường.',
    kanjiDeconstruction: ['飛 (PHI: bay)', '出 (XUẤT: ra)'],
    logicalAnchor: 'Chuyển động nhanh chóng ra ngoài.',
    collocation: '子供が道に飛び出す (Trẻ em lao ra đường)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-91',
    word: '必死な',
    reading: 'ひっしな',
    meaning: 'Quyết tâm, liều mạng',
    furigana: '必(ひっ)死(し)な',
    visualClue: 'Một người đang cố gắng hết sức để chạy về đích.',
    soundMnemonic: 'Hít shi na.',
    wackyStory: 'Dốc hết sức lực.',
    kanjiDeconstruction: ['必 (TẤT: chắc chắn)', '死 (TỬ: chết)'],
    logicalAnchor: 'Cố gắng hết sức mình.',
    collocation: '必死に勉強する (Liều mạng học hành)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-92',
    word: 'もう少しで',
    reading: 'もうすこしで',
    meaning: 'Thêm một ít nữa, suýt nữa thì',
    furigana: 'もう少(すこ)しで',
    visualClue: 'Chỉ còn một chút xíu nữa là đạt được.',
    soundMnemonic: 'Mô sư cô shi đê.',
    wackyStory: 'Chỉ còn một chút nữa thôi.',
    kanjiDeconstruction: ['少 (THIỂU: ít)'],
    logicalAnchor: 'Gần đến trạng thái hoặc kết quả nào đó.',
    collocation: 'もう少しで終わる (Sắp xong rồi)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-93',
    word: 'あはは',
    reading: 'あはは',
    meaning: 'Tiếng cười to',
    furigana: 'あはは',
    visualClue: 'Một người đang há miệng cười lớn.',
    soundMnemonic: 'A ha ha.',
    wackyStory: 'Cười to sảng khoái.',
    kanjiDeconstruction: [],
    logicalAnchor: 'Từ tượng thanh cho tiếng cười lớn.',
    collocation: 'あははと笑う (Cười lớn tiếng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-94',
    word: '女子高生',
    reading: 'じょしこうせい',
    meaning: 'Nữ sinh cấp ba',
    furigana: '女(じょ)子(し)高(こう)生(せい)',
    visualClue: 'Một nữ sinh trung học phổ thông.',
    soundMnemonic: 'Jô shi kô sê.',
    wackyStory: 'Nữ sinh đi học.',
    kanjiDeconstruction: ['女 (NỮ)', '子 (TỬ)', '高 (CAO)', '生 (SINH)'],
    logicalAnchor: 'Học sinh nữ trường cấp 3.',
    collocation: '女子高生たち (Các nữ sinh cấp 3)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-95',
    word: '男',
    reading: 'おとこ',
    meaning: 'Con trai / Đàn ông',
    furigana: '男(おとこ)',
    visualClue: 'Một người con trai.',
    soundMnemonic: 'Ô tô cô.',
    wackyStory: 'Người đàn ông mạnh mẽ.',
    kanjiDeconstruction: ['男 (NAM)'],
    logicalAnchor: 'Giới tính nam.',
    collocation: '男の人 (Người đàn ông)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-96',
    word: '女',
    reading: 'おんな',
    meaning: 'Con gái / Phụ nữ',
    furigana: '女(おんな)',
    visualClue: 'Một người con gái.',
    soundMnemonic: 'Ôn na.',
    wackyStory: 'Người phụ nữ xinh đẹp.',
    kanjiDeconstruction: ['女 (NỮ)'],
    logicalAnchor: 'Giới tính nữ.',
    collocation: '女の人 (Người phụ nữ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-97',
    word: '男女',
    reading: 'だんじょ',
    meaning: 'Trai gái, nam nữ',
    furigana: '男(だん)女(じょ)',
    visualClue: 'Một nam và một nữ đi cạnh nhau.',
    soundMnemonic: 'Đan jô.',
    wackyStory: 'Nam và nữ cùng nhau.',
    kanjiDeconstruction: ['男 (NAM)', '女 (NỮ)'],
    logicalAnchor: 'Cả hai giới tính.',
    collocation: '男女平等 (Bình đẳng nam nữ)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-98',
    word: '若者',
    reading: 'わかもの',
    meaning: 'Giới trẻ / Thanh niên',
    furigana: '若(わか)者(もの)',
    visualClue: 'Những người trẻ tuổi năng động.',
    soundMnemonic: 'Wa ka mô nô.',
    wackyStory: 'Người trẻ đầy nhiệt huyết.',
    kanjiDeconstruction: ['若 (NHƯỢC: trẻ)', '者 (GIẢ: người)'],
    logicalAnchor: 'Thế hệ trẻ.',
    collocation: '最近の若者 (Giới trẻ dạo gần đây)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-99',
    word: '目上',
    reading: 'めうえ',
    meaning: 'Người bề trên',
    furigana: '目(め)上(うえ)',
    visualClue: 'Nhìn lên người lớn tuổi hoặc cấp trên.',
    soundMnemonic: 'Mê ư ê.',
    wackyStory: 'Ánh mắt hướng lên người lớn tuổi.',
    kanjiDeconstruction: ['目 (MỤC: mắt)', '上 (THƯỢNG: trên)'],
    logicalAnchor: 'Người có địa vị hoặc tuổi tác cao hơn.',
    collocation: '目上の人 (Người bề trên)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-100',
    word: '使い分ける',
    reading: 'つかいわける',
    meaning: 'Chọn cách dùng (tùy theo hoàn cảnh)',
    furigana: '使(つか)い分(わ)ける',
    visualClue: 'Phân loại công cụ để sử dụng cho từng mục đích.',
    soundMnemonic: 'Tsu kai wa kê rự.',
    wackyStory: 'Chia ra để sử dụng.',
    kanjiDeconstruction: ['使 (SỬ: sử dụng)', '分 (PHÂN: chia)'],
    logicalAnchor: 'Sử dụng theo từng tình huống.',
    collocation: '言葉を使い分ける (Chọn từ ngữ để dùng)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-101',
    word: '我慢する',
    reading: 'がまんする',
    meaning: 'Chịu đựng',
    furigana: '我(が)慢(まん)する',
    visualClue: 'Một người cắn răng nhẫn nhịn.',
    soundMnemonic: 'Ga man sư rự.',
    wackyStory: 'Cố gắng chịu đựng cơn đau.',
    kanjiDeconstruction: ['我 (NGÃ: bản thân)', '慢 (MẠN: từ từ, kiêu ngạo)'],
    logicalAnchor: 'Kiềm chế cảm xúc, nhẫn nại.',
    collocation: '痛みを我慢する (Chịu đựng cơn đau)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-102',
    word: '疑問',
    reading: 'ぎもん',
    meaning: 'Sự nghi vấn, thắc mắc',
    furigana: '疑(ぎ)問(もん)',
    visualClue: 'Dấu chấm hỏi lớn trên đầu.',
    soundMnemonic: 'Gi môn.',
    wackyStory: 'Hỏi để giải đáp nghi ngờ.',
    kanjiDeconstruction: ['疑 (NGHI: nghi ngờ)', '問 (VẤN: hỏi)'],
    logicalAnchor: 'Điều chưa rõ cần được giải đáp.',
    collocation: '疑問に思う (Cảm thấy nghi vấn)',
    lessonId: 'lesson-9'
  },
  {
    id: 'vocab-9-103',
    word: '違い',
    reading: 'ちがい',
    meaning: 'Sự khác biệt',
    furigana: '違(ちが)い',
    visualClue: 'So sánh hai hình ảnh để tìm điểm khác biệt.',
    soundMnemonic: 'Chi gai.',
    wackyStory: 'Có sự sai khác.',
    kanjiDeconstruction: ['違 (VI: khác, sai)'],
    logicalAnchor: 'Sự không giống nhau.',
    collocation: '男女の違い (Sự khác biệt nam nữ)',
    lessonId: 'lesson-9'
  }
];