import { Vocabulary } from './types';

export const lesson10Words: Vocabulary[] = [
  {
    id: 'vocab-10-1',
    word: '世界自然遺産',
    reading: 'せかいしぜんいさん',
    meaning: 'Di sản thiên nhiên thế giới',
    furigana: '世界自然遺産',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-2',
    word: '観光地',
    reading: 'かんこうち',
    meaning: 'Điểm tham quan, khu du lịch',
    furigana: '観光地',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-3',
    word: '名所',
    reading: 'めいしょ',
    meaning: 'Danh lam thắng cảnh',
    furigana: '名所',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '紅葉の名所',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-4',
    word: '豊かさ',
    reading: 'ゆたかさ',
    meaning: 'Sự phong phú',
    furigana: '豊かさ',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '自然の豊かさ',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-5',
    word: '青空',
    reading: 'あおぞら',
    meaning: 'Bầu trời xanh',
    furigana: '青空',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '雲一つない青空',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-6',
    word: '日常',
    reading: 'にちじょう',
    meaning: 'Thường ngày',
    furigana: '日常',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '日常生活を忘れ',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-7',
    word: 'パンフレット',
    reading: 'パンフレット',
    meaning: 'Tờ rơi quảng cáo, sách hướng dẫn du lịch',
    furigana: 'パンフレット',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-8',
    word: '体験',
    reading: 'たいけん',
    meaning: 'Trải nghiệm',
    furigana: '体験',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '屋久島の自然と地元の料理を体験できる',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-9',
    word: 'トレッキング',
    reading: 'トレッキング',
    meaning: 'Đi bộ đường dài, leo núi khám phá(Trekking)',
    furigana: 'トレッキング',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-10',
    word: '所要時間',
    reading: 'しょようじかん',
    meaning: 'Thời gian cần thiết(thời gian dự kiến cho một hoạt động)',
    furigana: '所要時間',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-11',
    word: '歩行距離',
    reading: 'ほこうきょり',
    meaning: 'Cự ly đi bộ',
    furigana: '歩行距離',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-12',
    word: '往復',
    reading: 'おうふく',
    meaning: 'Khứ hồi, cả chiều đi lẫn chiều về(Thường đi kèm với số km hoặc thời gian)',
    furigana: '往復',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-13',
    word: '日帰り',
    reading: 'ひがえり',
    meaning: 'Đi về trong ngày',
    furigana: '日帰り',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '日帰りバスツアー',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-14',
    word: '海の幸',
    reading: 'うみのさち',
    meaning: 'Hải sản, sản vật từ biển',
    furigana: '海の幸',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-15',
    word: '山の幸',
    reading: 'やまのさち',
    meaning: 'Đặc sản vùng núi, sản vật từ núi',
    furigana: '山の幸',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-16',
    word: '名物',
    reading: 'めいぶつ',
    meaning: 'Đặc sản địa phương',
    furigana: '名物',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-17',
    word: 'おやつ',
    reading: 'おやつ',
    meaning: 'Đồ ăn vặt',
    furigana: 'おやつ',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-18',
    word: 'おつまみ',
    reading: 'おつまみ',
    meaning: 'Đồ nhắm rượu',
    furigana: 'おつまみ',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: 'ビールのおつまみ',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-19',
    word: '民宿',
    reading: 'みんしゅく',
    meaning: 'Nhà trọ kiểu Nhật(homestay do người dân địa phương kinh doanh)',
    furigana: '民宿',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-20',
    word: '城 / お城',
    reading: 'しろ / おしろ',
    meaning: 'Lâu đài.',
    furigana: '城 / お城',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-21',
    word: '天守閣',
    reading: 'てんしゅかく',
    meaning: 'Tháp canh chính của lâu đài, tháp trung tâm.',
    furigana: '天守閣',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-22',
    word: '屋根',
    reading: 'やね',
    meaning: 'Mái nhà.',
    furigana: '屋根',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-23',
    word: '鯱',
    reading: 'しゃちほこ',
    meaning: 'Tượng con vật huyền thoại mình cá đầu hổ(thường được đặt trên mái nhà của các lâu đài Nhật Bản).',
    furigana: '鯱',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-24',
    word: '金',
    reading: 'きん',
    meaning: 'Vàng(Ví dụ: 金の鯱 - Tượng Shachihoko bằng vàng).',
    furigana: '金',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-25',
    word: '虎',
    reading: 'とら',
    meaning: 'Con hổ.',
    furigana: '虎',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-26',
    word: '神社',
    reading: 'じんじゃ',
    meaning: 'Đền thần.',
    furigana: '神社',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-27',
    word: '建物',
    reading: 'たてもの',
    meaning: 'Tòa nhà, công trình kiến trúc.',
    furigana: '建物',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-28',
    word: '国宝',
    reading: 'こくほう',
    meaning: 'Quốc bảo, báu vật quốc gia.',
    furigana: '国宝',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-29',
    word: '彫刻',
    reading: 'ちょうこく',
    meaning: 'Điêu khắc, bức chạm khắc.',
    furigana: '彫刻',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-30',
    word: '豪華さ',
    reading: 'ごうかさ',
    meaning: 'Sự nguy nga, tráng lệ.',
    furigana: '豪華さ',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-31',
    word: '誇り',
    reading: 'ほこり',
    meaning: 'Niềm tự hào(Ví dụ: 名古屋の人々はこのお城を誇りにしています - Người dân Nagoya rất tự hào về tòa lâu đài này).',
    furigana: '誇り',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-32',
    word: '登録されている',
    reading: 'とうろくされている',
    meaning: 'Được đăng ký(Thường đi với cụm: 世界遺産に登録されている - Được đăng ký là Di sản thế giới).',
    furigana: '登録されている',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-33',
    word: '指定されている',
    reading: 'していされている',
    meaning: 'Được chỉ định(Thường đi với cụm: 国宝に指定されている - Được chỉ định làm Quốc bảo).',
    furigana: '指定されている',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-34',
    word: '戦争',
    reading: 'せんそう',
    meaning: 'Chiến tranh.',
    furigana: '戦争',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-35',
    word: '焼ける',
    reading: 'やける',
    meaning: 'Bị thiêu rụi, bị cháy(Ví dụ: Chiến tranh đã làm lâu đài bị thiêu rụi).',
    furigana: '焼ける',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-36',
    word: '火事',
    reading: 'かじ',
    meaning: 'Hỏa hoạn.',
    furigana: '火事',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-37',
    word: '災害',
    reading: 'さいがい',
    meaning: 'Thảm họa, tai họa(Ví dụ: 災害から守る - Bảo vệ khỏi tai họa / hỏa hoạn).',
    furigana: '災害',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-38',
    word: '指定席',
    reading: 'していせき',
    meaning: 'Ghế chỉ định, ghế đặt chỗ trước.',
    furigana: '指定席',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-39',
    word: '自由席',
    reading: 'じゆうせき',
    meaning: 'Ghế tự do, ghế không cần đặt trước.',
    furigana: '自由席',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-40',
    word: 'グリーン車',
    reading: 'グリーンしゃ',
    meaning: 'Toa hạng nhất(Toa Green, thường có ghế ngồi rộng và thoải mái hơn).',
    furigana: 'グリーン車',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-41',
    word: '座席',
    reading: 'ざせき',
    meaning: 'Chỗ ngồi.',
    furigana: '座席',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-42',
    word: '車両',
    reading: 'しゃりょう',
    meaning: 'Toa xe, xe cộ nói chung.',
    furigana: '車両',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-43',
    word: '～号車',
    reading: 'ごうしゃ',
    meaning: 'Toa số... (Ví dụ: 1号車 - Toa số 1).',
    furigana: '～号車',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-44',
    word: 'デッキ',
    reading: 'デッキ',
    meaning: 'Khu vực boong nối giữa các toa tàu.',
    furigana: 'デッキ',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-45',
    word: '車内',
    reading: 'しゃない',
    meaning: 'Trong tàu, trong xe.',
    furigana: '車内',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-46',
    word: '販売',
    reading: 'はんばい',
    meaning: 'Bán hàng.Thường đi liền thành cụm車内販売(しゃないはんばい): Dịch vụ bán hàng trên tàu(như bán cơm hộp, trà...).',
    furigana: '販売',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-47',
    word: '車掌',
    reading: 'しゃしょう',
    meaning: 'Trưởng tàu, nhân viên soát vé.',
    furigana: '車掌',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-48',
    word: '停車駅',
    reading: 'ていしゃえき',
    meaning: 'Ga dừng, các trạm tàu sẽ dừng lại.',
    furigana: '停車駅',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-49',
    word: '終点',
    reading: 'しゅうてん',
    meaning: 'Ga cuối cùng.',
    furigana: '終点',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-50',
    word: '満席',
    reading: 'まんせき',
    meaning: 'Kín chỗ, hết chỗ.',
    furigana: '満席',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-51',
    word: '全席満席',
    reading: 'ぜんせきまんせき',
    meaning: 'Toàn bộ ghế đã kín chỗ.',
    furigana: '全席満席',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-52',
    word: '全席禁煙',
    reading: 'ぜんせききんえん',
    meaning: 'Cấm hút thuốc tại toàn bộ các ghế.',
    furigana: '全席禁煙',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-53',
    word: '通話',
    reading: 'つうわ',
    meaning: 'Gọi điện thoại(Thường được nhắc nhở hạn chế ở khu vực ghế ngồi: お席での通話はご遠慮ください - Xin quý khách hạn chế gọi điện thoại tại chỗ ngồi).',
    furigana: '通話',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-54',
    word: 'まもなく',
    reading: 'まもなく',
    meaning: 'Sắp sửa, chuẩn bị(Ví dụ: まもなく到着します - Sắp đến nơi).',
    furigana: 'まもなく',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-55',
    word: 'なお',
    reading: 'なお',
    meaning: 'Ngoài ra, thêm vào đó(Từ nối thường dùng để bổ sung thông tin trong phát thanh).',
    furigana: 'なお',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-56',
    word: 'あらかじめ',
    reading: 'あらかじめ',
    meaning: '(Chuẩn bị / Thông cảm) sẵn, từ trước.',
    furigana: 'あらかじめ',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-57',
    word: 'あらかじめご了承ください',
    reading: 'あらかじめご了承ください',
    meaning: 'Xin quý khách vui lòng thông cảm / hiểu cho(Đây là một cụm từ cố định vô cùng phổ biến ở cuối mỗi bản tin thông báo trên tàu).',
    furigana: 'あらかじめご了承ください',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-58',
    word: '忘れ物',
    reading: 'わすれもの',
    meaning: 'Đồ bỏ quên, đồ thất lạc.',
    furigana: '忘れ物',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-59',
    word: 'カーディガン',
    reading: 'カーディガン',
    meaning: 'Áo khoác len mỏng(cardigan).',
    furigana: 'カーディガン',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-60',
    word: 'スマートフォン / スマホ',
    reading: 'スマートフォン / スマホ',
    meaning: 'Điện thoại thông minh.',
    furigana: 'スマートフォン / スマホ',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-61',
    word: '窓側の奥の席',
    reading: 'まどがわのおくのせき',
    meaning: 'Ghế trong góc phía cửa sổ.',
    furigana: '窓側の奥の席',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-62',
    word: '洗面台',
    reading: 'せんめんだい',
    meaning: 'Bồn rửa mặt(Ví dụ: để quên điện thoại trên bồn rửa mặt trong nhà vệ sinh).',
    furigana: '洗面台',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-63',
    word: '特徴',
    reading: 'とくちょう',
    meaning: 'Đặc trưng, đặc điểm nhận dạng.',
    furigana: '特徴',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-64',
    word: '胸',
    reading: 'むね',
    meaning: 'Ngực(Ví dụ: ngực áo).',
    furigana: '胸',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-65',
    word: 'マーク',
    reading: 'マーク',
    meaning: 'Dấu hiệu, logo(Ví dụ: 胸にペンギンのマーク - Có logo hình chim cánh cụt ở trước ngực).',
    furigana: 'マーク',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-66',
    word: '気が付く',
    reading: 'きがつく',
    meaning: 'Nhận ra(Ví dụ: 帰りの新幹線の中で、そのことに気が付きました - Trên chuyến tàu Shinkansen lúc về thì mới nhận ra việc đó).',
    furigana: '気が付く',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-67',
    word: '問い合わせる',
    reading: 'といあわせる',
    meaning: 'Hỏi thăm, liên hệ để hỏi thông tin.',
    furigana: '問い合わせる',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-68',
    word: '落ちる',
    reading: 'おちる',
    meaning: 'Rơi(Ví dụ: 下に落ちている - Rơi xuống dưới).',
    furigana: '落ちる',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-69',
    word: 'はっきり覚えている',
    reading: 'はっきりおぼえている',
    meaning: 'Nhớ rõ(Thường dùng ở thể phủ định: はっきり覚えていないんですが - Tôi không nhớ rõ lắm nhưng...).',
    furigana: 'はっきり覚えている',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-70',
    word: '宅配便',
    reading: 'たくはいびん',
    meaning: 'Dịch vụ chuyển phát tận nhà.',
    furigana: '宅配便',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-71',
    word: '着払い',
    reading: 'ちゃくばらい',
    meaning: 'Thanh toán cước khi nhận hàng(người nhận trả phí ship).',
    furigana: '着払い',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-72',
    word: '感動する',
    reading: 'かんどうする',
    meaning: 'Cảm động.',
    furigana: '感動する',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-73',
    word: 'びっくりする / 驚く',
    reading: 'おどろく',
    meaning: 'Ngạc nhiên, giật mình.',
    furigana: 'びっくりする / 驚く',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-74',
    word: 'わくわくする',
    reading: 'わくわくする',
    meaning: 'Hào hứng, hồi hộp(cảm giác vui sướng, mong chờ).',
    furigana: 'わくわくする',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-75',
    word: 'がっかりする',
    reading: 'がっかりする',
    meaning: 'Thất vọng.',
    furigana: 'がっかりする',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-76',
    word: 'いらいらする',
    reading: 'いらいらする',
    meaning: 'Khó chịu, bực bội.',
    furigana: 'いらいらする',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-77',
    word: '神秘的（な）',
    reading: 'しんぴてきな',
    meaning: 'Mang tính thần bí, huyền bí.',
    furigana: '神秘的（な）',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-78',
    word: '豪華さ',
    reading: 'ごうかさ',
    meaning: 'Sự nguy nga, tráng lệ.',
    furigana: '豪華さ',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-79',
    word: '立派（な）',
    reading: 'りっぱな',
    meaning: 'Tuyệt vời, hoành tráng.',
    furigana: '立派（な）',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-80',
    word: '迫力満点',
    reading: 'はくりょくまんてん',
    meaning: 'Sức mạnh vô cùng lớn, sức lôi cuốn mạnh mẽ(thường miêu tả thiên nhiên hùng vĩ như thác nước).',
    furigana: '迫力満点',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-81',
    word: '印象',
    reading: 'いんしょう',
    meaning: 'Ấn tượng.',
    furigana: '印象',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-82',
    word: '大満足',
    reading: 'だいまんぞく',
    meaning: 'Rất mãn nguyện, rất hài lòng.',
    furigana: '大満足',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-83',
    word: '幸運なことに',
    reading: 'こううんなことに',
    meaning: 'Thật may mắn là....',
    furigana: '幸運なことに',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-84',
    word: '残念なことに',
    reading: 'ざんねんなことに',
    meaning: 'Thật đáng tiếc là....',
    furigana: '残念なことに',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-85',
    word: '嬉しいことに',
    reading: 'うれしいことに',
    meaning: 'Thật vui là....',
    furigana: '嬉しいことに',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
  {
    id: 'vocab-10-86',
    word: '驚いたことに',
    reading: 'おどろいたことに',
    meaning: 'Thật ngạc nhiên là....',
    furigana: '驚いたことに',
    visualClue: '',
    soundMnemonic: '',
    wackyStory: '',
    kanjiDeconstruction: [],
    logicalAnchor: '',
    collocation: '',
    lessonId: 'lesson-10'
  },
];
