import { Vocabulary } from './types';

export const lesson10Words: Vocabulary[] = [
    {
        id: 'vocab-10-1',
        word: '世界自然遺産',
        reading: 'せかいしぜんいさん',
        meaning: 'Di sản thiên nhiên thế giới',
        furigana: '世(せ)界(かい)自(し)然(ぜん)遺(い)産(さん)',
        visualClue: 'Một khu rừng nguyên sinh được UNESCO công nhận.',
        soundMnemonic: 'Sê cai shi zen i san.',
        wackyStory: 'Di sản thiên nhiên thế giới cần được bảo vệ.',
        kanjiDeconstruction: ['世 (THẾ)', '界 (GIỚI)', '自 (TỰ)', '然 (NHIÊN)', '遺 (DI)', '産 (SẢN)'],
        logicalAnchor: 'Khu vực có giá trị nổi bật về thiên nhiên.',
        collocation: '世界自然遺産に登録される (Được đăng ký là Di sản thiên nhiên thế giới)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-2',
        word: '観光地',
        reading: 'かんこうち',
        meaning: 'Điểm tham quan, khu du lịch',
        furigana: '観(かん)光(こう)地(ち)',
        visualClue: 'Một địa điểm đông đúc du khách.',
        soundMnemonic: 'Kan cô chi.',
        wackyStory: 'Khách du lịch đông nghẹt ở điểm tham quan.',
        kanjiDeconstruction: ['観 (QUAN)', '光 (QUANG)', '地 (ĐỊA)'],
        logicalAnchor: 'Nơi thu hút du lịch.',
        collocation: '有名な観光地 (Khu du lịch nổi tiếng)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-3',
        word: '名所',
        reading: 'めいしょ',
        meaning: 'Danh lam thắng cảnh',
        furigana: '名(めい)所(しょ)',
        visualClue: 'Một phong cảnh nổi tiếng đẹp mắt.',
        soundMnemonic: 'Mê shô.',
        wackyStory: 'Nơi có tên tuổi.',
        kanjiDeconstruction: ['名 (DANH)', '所 (SỞ)'],
        logicalAnchor: 'Địa điểm nổi tiếng về cảnh đẹp.',
        collocation: '紅葉の名所 (Danh thắng ngắm lá đỏ)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-4',
        word: '豊かさ',
        reading: 'ゆたかさ',
        meaning: 'Sự phong phú',
        furigana: '豊(ゆた)かさ',
        visualClue: 'Một rương đầy vàng bạc châu báu, hoặc thiên nhiên xanh tươi.',
        soundMnemonic: 'Yu ta ca sa.',
        wackyStory: 'Nhiều thứ dồi dào, phong phú.',
        kanjiDeconstruction: ['豊 (PHONG)'],
        logicalAnchor: 'Trạng thái có nhiều, dư dả.',
        collocation: '自然の豊かさ (Sự phong phú của thiên nhiên)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-5',
        word: '青空',
        reading: 'あおぞら',
        meaning: 'Bầu trời xanh',
        furigana: '青(あお)空(ぞら)',
        visualClue: 'Bầu trời trong xanh không một gợn mây.',
        soundMnemonic: 'A ô zô ra.',
        wackyStory: 'Trời xanh thẳm.',
        kanjiDeconstruction: ['青 (THANH)', '空 (KHÔNG)'],
        logicalAnchor: 'Trạng thái trời trong, không mây.',
        collocation: '雲一つない青空 (Bầu trời xanh không một gợn mây)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-6',
        word: '日常',
        reading: 'にちじょう',
        meaning: 'Thường ngày',
        furigana: '日(にち)常(じょう)',
        visualClue: 'Các hoạt động lặp đi lặp lại hàng ngày.',
        soundMnemonic: 'Ni chi jô.',
        wackyStory: 'Ngày nào cũng như ngày nào.',
        kanjiDeconstruction: ['日 (NHẬT)', '常 (THƯỜNG)'],
        logicalAnchor: 'Những thứ bình thường mỗi ngày.',
        collocation: '日常生活を忘れ (Quên đi cuộc sống thường ngày)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-7',
        word: 'パンフレット',
        reading: 'パンフレット',
        meaning: 'Tờ rơi quảng cáo, sách hướng dẫn du lịch',
        furigana: 'パンフレット',
        visualClue: 'Một tờ bướm gấp làm ba quảng cáo tour du lịch.',
        soundMnemonic: 'Pan fư rết tô.',
        wackyStory: 'Phát tờ rơi trên phố.',
        kanjiDeconstruction: [],
        logicalAnchor: 'Tài liệu in ấn nhỏ để giới thiệu.',
        collocation: 'パンフレットを見る (Xem sách hướng dẫn du lịch)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-8',
        word: '体験',
        reading: 'たいけん',
        meaning: 'Trải nghiệm',
        furigana: '体(たい)験(けん)',
        visualClue: 'Một người đang tự tay làm gốm.',
        soundMnemonic: 'Tai ken.',
        wackyStory: 'Tự bản thân trải qua.',
        kanjiDeconstruction: ['体 (THỂ)', '験 (NGHIỆM)'],
        logicalAnchor: 'Việc tự mình kinh qua để có kinh nghiệm.',
        collocation: '屋久島の自然と地元の料理を体験できる (Có thể trải nghiệm thiên nhiên và ẩm thực địa phương Yakushima)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-9',
        word: 'トレッキング',
        reading: 'トレッキング',
        meaning: 'Đi bộ đường dài, leo núi khám phá (Trekking)',
        furigana: 'トレッキング',
        visualClue: 'Một người mang balo lớn đang đi bộ trong rừng.',
        soundMnemonic: 'Tô rếk kin gư.',
        wackyStory: 'Đi bộ xuyên rừng.',
        kanjiDeconstruction: [],
        logicalAnchor: 'Hoạt động dã ngoại dài ngày.',
        collocation: 'トレッキングに参加する (Tham gia trekking)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-10',
        word: '所要時間',
        reading: 'しょようじかん',
        meaning: 'Thời gian cần thiết',
        furigana: '所(しょ)要(よう)時(じ)間(かん)',
        visualClue: 'Một chiếc đồng hồ bấm giờ đếm ngược.',
        soundMnemonic: 'Shô yô ji can.',
        wackyStory: 'Mất bao lâu để làm việc này?',
        kanjiDeconstruction: ['所 (SỞ)', '要 (YẾU)', '時 (THỜI)', '間 (GIAN)'],
        logicalAnchor: 'Lượng thời gian dự kiến để hoàn thành.',
        collocation: '所要時間は2時間です (Thời gian cần thiết là 2 tiếng)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-11',
        word: '歩行距離',
        reading: 'ほこうきょり',
        meaning: 'Cự ly đi bộ',
        furigana: '歩(ほ)行(こう)距(きょ)離(り)',
        visualClue: 'Biển báo chỉ số km trên đường mòn.',
        soundMnemonic: 'Hô cô cyô ri.',
        wackyStory: 'Khoảng cách phải bước đi.',
        kanjiDeconstruction: ['歩 (BỘ)', '行 (HÀNH)', '距 (CỰ)', '離 (LY)'],
        logicalAnchor: 'Độ dài đoạn đường đi bộ.',
        collocation: '歩行距離は約5キロです (Cự ly đi bộ là khoảng 5km)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-12',
        word: '往復',
        reading: 'おうふく',
        meaning: 'Khứ hồi',
        furigana: '往(おう)復(ふく)',
        visualClue: 'Mũi tên hai chiều đi và về.',
        soundMnemonic: 'Ô fư cư.',
        wackyStory: 'Đi rồi quay lại.',
        kanjiDeconstruction: ['往 (VÃNG)', '復 (PHỤC)'],
        logicalAnchor: 'Hành trình cả hai chiều.',
        collocation: '往復のチケット (Vé khứ hồi)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-13',
        word: '日帰り',
        reading: 'ひがえり',
        meaning: 'Đi về trong ngày',
        furigana: '日(ひ)帰(がえ)り',
        visualClue: 'Đi ra khỏi nhà lúc sáng và về lúc tối.',
        soundMnemonic: 'Hi ga ê ri.',
        wackyStory: 'Trong ngày là về.',
        kanjiDeconstruction: ['日 (NHẬT)', '帰 (QUY)'],
        logicalAnchor: 'Chuyến đi không ngủ qua đêm.',
        collocation: '日帰りバスツアー (Tour xe buýt đi về trong ngày)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-14',
        word: '海の幸',
        reading: 'うみのさち',
        meaning: 'Hải sản',
        furigana: '海(うみ)の幸(さち)',
        visualClue: 'Một mâm tôm cua cá tươi rói.',
        soundMnemonic: 'Ư mi nô sa chi.',
        wackyStory: 'Hạnh phúc từ biển cả.',
        kanjiDeconstruction: ['海 (HẢI)', '幸 (HẠNH)'],
        logicalAnchor: 'Sản vật biển.',
        collocation: '新鮮な海の幸 (Hải sản tươi sống)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-15',
        word: '山の幸',
        reading: 'やまのさち',
        meaning: 'Đặc sản vùng núi',
        furigana: '山(やま)の幸(さち)',
        visualClue: 'Nấm, măng, thú rừng.',
        soundMnemonic: 'Ya ma nô sa chi.',
        wackyStory: 'Hạnh phúc từ rừng núi.',
        kanjiDeconstruction: ['山 (SƠN)', '幸 (HẠNH)'],
        logicalAnchor: 'Sản vật miền núi.',
        collocation: '秋の山の幸 (Đặc sản núi rừng mùa thu)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-16',
        word: '名物',
        reading: 'めいぶつ',
        meaning: 'Đặc sản địa phương',
        furigana: '名(めい)物(ぶつ)',
        visualClue: 'Món ăn nổi tiếng mang tên một vùng đất.',
        soundMnemonic: 'Mê bư tsu.',
        wackyStory: 'Đồ vật/món ăn có danh tiếng.',
        kanjiDeconstruction: ['名 (DANH)', '物 (VẬT)'],
        logicalAnchor: 'Sản phẩm đặc trưng.',
        collocation: 'この町の名物 (Đặc sản của thị trấn này)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-17',
        word: 'おやつ',
        reading: 'おやつ',
        meaning: 'Đồ ăn vặt',
        furigana: 'おやつ',
        visualClue: 'Bánh kẹo, trái cây ăn nhẹ giữa buổi.',
        soundMnemonic: 'Ô ya tsu.',
        wackyStory: 'Bữa ăn phụ.',
        kanjiDeconstruction: [],
        logicalAnchor: 'Thức ăn nhẹ, quà vặt.',
        collocation: '3時のおやつ (Bữa ăn vặt lúc 3 giờ)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-18',
        word: 'おつまみ',
        reading: 'おつまみ',
        meaning: 'Đồ nhắm rượu',
        furigana: 'おつまみ',
        visualClue: 'Đậu phộng, khô mực để nhắm bia.',
        soundMnemonic: 'Ô tsu ma mi.',
        wackyStory: 'Bốc nhón đồ nhắm.',
        kanjiDeconstruction: [],
        logicalAnchor: 'Thức ăn đi kèm khi uống đồ có cồn.',
        collocation: 'ビールのおつまみ (Mồi nhắm bia)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-19',
        word: '民宿',
        reading: 'みんしゅく',
        meaning: 'Nhà trọ kiểu Nhật',
        furigana: '民(みん)宿(しゅく)',
        visualClue: 'Một ngôi nhà truyền thống Nhật Bản cho khách du lịch thuê.',
        soundMnemonic: 'Min shư cư.',
        wackyStory: 'Ngủ trọ nhà dân.',
        kanjiDeconstruction: ['民 (DÂN)', '宿 (TÚC)'],
        logicalAnchor: 'Chỗ ở do người dân địa phương kinh doanh.',
        collocation: '民宿に泊まる (Trọ lại homestay/nhà dân)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-20',
        word: 'お城',
        reading: 'おしろ',
        meaning: 'Lâu đài',
        furigana: 'お城(しろ)',
        visualClue: 'Lâu đài Nhật Bản với mái ngói cong.',
        soundMnemonic: 'Ô shi rô.',
        wackyStory: 'Thành quách nguy nga.',
        kanjiDeconstruction: ['城 (THÀNH)'],
        logicalAnchor: 'Công trình phòng thủ kiêm dinh thự lãnh chúa.',
        collocation: '名古屋城 (Lâu đài Nagoya)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-21',
        word: '天守閣',
        reading: 'てんしゅかく',
        meaning: 'Tháp canh chính, tháp trung tâm',
        furigana: '天(てん)守(しゅ)閣(かく)',
        visualClue: 'Tòa tháp cao nhất nằm giữa lâu đài.',
        soundMnemonic: 'Ten shư ca cư.',
        wackyStory: 'Gác bảo vệ bầu trời.',
        kanjiDeconstruction: ['天 (THIÊN)', '守 (THỦ)', '閣 (CÁC)'],
        logicalAnchor: 'Phần cấu trúc quan trọng nhất của lâu đài Nhật Bản.',
        collocation: '天守閣に上る (Lên tháp canh chính)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-22',
        word: '屋根',
        reading: 'やね',
        meaning: 'Mái nhà',
        furigana: '屋(や)根(ね)',
        visualClue: 'Phần che mưa che nắng phía trên cùng của ngôi nhà.',
        soundMnemonic: 'Ya nê.',
        wackyStory: 'Gốc rễ của căn nhà úp ngược.',
        kanjiDeconstruction: ['屋 (ỐC)', '根 (CĂN)'],
        logicalAnchor: 'Cấu trúc phủ mái.',
        collocation: '屋根の上 (Trên mái nhà)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-23',
        word: '鯱',
        reading: 'しゃちほこ',
        meaning: 'Tượng con vật huyền thoại mình cá đầu hổ',
        furigana: '鯱(しゃちほこ)',
        visualClue: 'Tượng đặt chóp mái lâu đài uốn cong đuôi lên.',
        soundMnemonic: 'Sha chi hô cô.',
        wackyStory: 'Quái vật cá hổ.',
        kanjiDeconstruction: ['鯱 (HỔ)'],
        logicalAnchor: 'Linh vật bảo vệ lâu đài khỏi hỏa hoạn.',
        collocation: '金の鯱 (Tượng Shachihoko bằng vàng)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-24',
        word: '金',
        reading: 'きん',
        meaning: 'Vàng',
        furigana: '金(きん)',
        visualClue: 'Thỏi vàng lấp lánh.',
        soundMnemonic: 'Kin.',
        wackyStory: 'Tiền vàng.',
        kanjiDeconstruction: ['金 (KIM)'],
        logicalAnchor: 'Kim loại quý màu vàng.',
        collocation: '金でできた指輪 (Nhẫn làm bằng vàng)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-25',
        word: '虎',
        reading: 'とら',
        meaning: 'Con hổ',
        furigana: '虎(とら)',
        visualClue: 'Con hổ vằn dũng mãnh.',
        soundMnemonic: 'Tô ra.',
        wackyStory: 'Hổ gầm rống.',
        kanjiDeconstruction: ['虎 (HỔ)'],
        logicalAnchor: 'Động vật hoang dã họ mèo lớn.',
        collocation: '虎の絵 (Bức tranh con hổ)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-26',
        word: '神社',
        reading: 'じんじゃ',
        meaning: 'Đền thần',
        furigana: '神(じん)社(じゃ)',
        visualClue: 'Cổng Torii màu đỏ ở lối vào.',
        soundMnemonic: 'Jin ja.',
        wackyStory: 'Nơi thờ thần linh.',
        kanjiDeconstruction: ['神 (THẦN)', '社 (XÃ)'],
        logicalAnchor: 'Cơ sở tôn giáo của Thần đạo.',
        collocation: '神社にお参りする (Đi viếng đền thần)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-27',
        word: '建物',
        reading: 'たてもの',
        meaning: 'Tòa nhà, công trình kiến trúc',
        furigana: '建(たて)物(もの)',
        visualClue: 'Tòa cao ốc hoặc các ngôi nhà lớn.',
        soundMnemonic: 'Ta tê mô nô.',
        wackyStory: 'Vật được xây dựng lên.',
        kanjiDeconstruction: ['建 (KIẾN)', '物 (VẬT)'],
        logicalAnchor: 'Kiến trúc được xây dựng.',
        collocation: '高い建物 (Tòa nhà cao tầng)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-28',
        word: '国宝',
        reading: 'こくほう',
        meaning: 'Quốc bảo, báu vật quốc gia',
        furigana: '国(こく)宝(ほう)',
        visualClue: 'Thanh kiếm cổ hoặc bức tượng Phật quý giá.',
        soundMnemonic: 'Cô cư hô.',
        wackyStory: 'Bảo vật của đất nước.',
        kanjiDeconstruction: ['国 (QUỐC)', '宝 (BẢO)'],
        logicalAnchor: 'Vật phẩm có giá trị cao nhất của quốc gia.',
        collocation: '国宝に指定される (Được chỉ định làm Quốc bảo)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-29',
        word: '彫刻',
        reading: 'ちょうこく',
        meaning: 'Điêu khắc',
        furigana: '彫(ちょう)刻(こく)',
        visualClue: 'Bức tượng được tạc từ gỗ hoặc đá.',
        soundMnemonic: 'Chô cô cư.',
        wackyStory: 'Chạm trổ tinh xảo.',
        kanjiDeconstruction: ['彫 (ĐIÊU)', '刻 (KHẮC)'],
        logicalAnchor: 'Nghệ thuật tạo hình không gian 3 chiều.',
        collocation: '木の彫刻 (Bức điêu khắc bằng gỗ)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-30',
        word: '豪華さ',
        reading: 'ごうかさ',
        meaning: 'Sự nguy nga, tráng lệ',
        furigana: '豪(ごう)華(か)さ',
        visualClue: 'Bên trong cung điện dát vàng.',
        soundMnemonic: 'Gô ca sa.',
        wackyStory: 'Sự sang trọng hào hoa.',
        kanjiDeconstruction: ['豪 (HÀO)', '華 (HOA)'],
        logicalAnchor: 'Trạng thái lộng lẫy, đắt tiền.',
        collocation: '建物の豪華さ (Sự tráng lệ của công trình kiến trúc)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-31',
        word: '誇り',
        reading: 'ほこり',
        meaning: 'Niềm tự hào',
        furigana: '誇(ほこ)り',
        visualClue: 'Ưỡn ngực đầy kiêu hãnh.',
        soundMnemonic: 'Hô cô ri.',
        wackyStory: 'Lòng tự tôn.',
        kanjiDeconstruction: ['誇 (KHOA)'],
        logicalAnchor: 'Cảm giác tự hào về điều gì đó.',
        collocation: 'お城を誇りにしている (Tự hào về lâu đài)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-32',
        word: '登録されている',
        reading: 'とうろくされている',
        meaning: 'Được đăng ký',
        furigana: '登(とう)録(ろく)されている',
        visualClue: 'Được ghi tên vào sổ sách.',
        soundMnemonic: 'Tô rô cư sa rê tê i rự.',
        wackyStory: 'Được ghi nhận chính thức.',
        kanjiDeconstruction: ['登 (ĐĂNG)', '録 (LỤC)'],
        logicalAnchor: 'Quá trình lưu lại hồ sơ thông tin.',
        collocation: '世界遺産に登録されている (Được đăng ký là Di sản thế giới)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-33',
        word: '指定されている',
        reading: 'していされている',
        meaning: 'Được chỉ định',
        furigana: '指(し)定(てい)されている',
        visualClue: 'Một ngón tay trỏ vào văn bản quyết định.',
        soundMnemonic: 'Shi tê sa rê tê i rự.',
        wackyStory: 'Được lựa chọn và công nhận.',
        kanjiDeconstruction: ['指 (CHỈ)', '定 (ĐỊNH)'],
        logicalAnchor: 'Được xác định để nhận một danh hiệu/vai trò.',
        collocation: '国宝に指定されている (Được chỉ định làm Quốc bảo)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-34',
        word: '戦争',
        reading: 'せんそう',
        meaning: 'Chiến tranh',
        furigana: '戦(せん)争(そう)',
        visualClue: 'Bom đạn và sự phá hủy.',
        soundMnemonic: 'Sen sô.',
        wackyStory: 'Đánh nhau khốc liệt.',
        kanjiDeconstruction: ['戦 (CHIẾN)', '争 (TRANH)'],
        logicalAnchor: 'Sự xung đột vũ trang.',
        collocation: '戦争が起きる (Xảy ra chiến tranh)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-35',
        word: '焼ける',
        reading: 'やける',
        meaning: 'Bị thiêu rụi, bị cháy',
        furigana: '焼(や)ける',
        visualClue: 'Ngọn lửa đang bốc lên thiêu đốt.',
        soundMnemonic: 'Ya kê rự.',
        wackyStory: 'Cháy thành tro.',
        kanjiDeconstruction: ['焼 (THIÊU)'],
        logicalAnchor: 'Trạng thái bị lửa thiêu hủy.',
        collocation: '戦争で焼けた (Bị thiêu rụi do chiến tranh)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-36',
        word: '火事',
        reading: 'かじ',
        meaning: 'Hỏa hoạn',
        furigana: '火(か)事(じ)',
        visualClue: 'Xe cứu hỏa đang phun nước.',
        soundMnemonic: 'Ca ji.',
        wackyStory: 'Sự việc có lửa.',
        kanjiDeconstruction: ['火 (HỎA)', '事 (SỰ)'],
        logicalAnchor: 'Tai nạn cháy.',
        collocation: '火事が起きる (Xảy ra hỏa hoạn)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-37',
        word: '災害',
        reading: 'さいがい',
        meaning: 'Thảm họa, tai họa',
        furigana: '災(さい)害(がい)',
        visualClue: 'Sóng thần, động đất, bão lụt.',
        soundMnemonic: 'Sai gai.',
        wackyStory: 'Thiên tai địch họa.',
        kanjiDeconstruction: ['災 (TAI)', '害 (HẠI)'],
        logicalAnchor: 'Sự kiện gây thiệt hại lớn.',
        collocation: '災害から守る (Bảo vệ khỏi thảm họa)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-38',
        word: '指定席',
        reading: 'していせき',
        meaning: 'Ghế chỉ định',
        furigana: '指(し)定(てい)席(せき)',
        visualClue: 'Ghế có ghi số cụ thể trên vé.',
        soundMnemonic: 'Shi tê se ki.',
        wackyStory: 'Chỗ ngồi được đặt trước.',
        kanjiDeconstruction: ['指 (CHỈ)', '定 (ĐỊNH)', '席 (TỊCH)'],
        logicalAnchor: 'Chỗ ngồi phải đặt vé trước mới được ngồi.',
        collocation: '指定席の切符 (Vé ghế chỉ định)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-39',
        word: '自由席',
        reading: 'じゆうせき',
        meaning: 'Ghế tự do',
        furigana: '自(じ)由(ゆう)席(せき)',
        visualClue: 'Khu vực toa xe ai đến trước ngồi trước.',
        soundMnemonic: 'Ji yuu se ki.',
        wackyStory: 'Ghế ngồi tự do thích ngồi đâu thì ngồi.',
        kanjiDeconstruction: ['自 (TỰ)', '由 (DO)', '席 (TỊCH)'],
        logicalAnchor: 'Chỗ ngồi không cần số ghế.',
        collocation: '自由席に座る (Ngồi ở ghế tự do)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-40',
        word: 'グリーン車',
        reading: 'グリーンしゃ',
        meaning: 'Toa hạng nhất',
        furigana: 'グリーン車(しゃ)',
        visualClue: 'Toa tàu sang trọng, ghế rộng.',
        soundMnemonic: 'Gư rin sha.',
        wackyStory: 'Toa xe màu xanh lá cây.',
        kanjiDeconstruction: ['車 (XA)'],
        logicalAnchor: 'Toa xe dịch vụ cao cấp.',
        collocation: 'グリーン車に乗る (Đi toa hạng nhất)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-41',
        word: '座席',
        reading: 'ざせき',
        meaning: 'Chỗ ngồi',
        furigana: '座(ざ)席(せき)',
        visualClue: 'Một cái ghế trên phương tiện công cộng.',
        soundMnemonic: 'Za se ki.',
        wackyStory: 'Chỗ để ngồi xuống.',
        kanjiDeconstruction: ['座 (TỌA)', '席 (TỊCH)'],
        logicalAnchor: 'Vị trí ngồi.',
        collocation: '座席を立つ (Rời khỏi chỗ ngồi)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-42',
        word: '車両',
        reading: 'しゃりょう',
        meaning: 'Toa xe, xe cộ',
        furigana: '車(しゃ)両(りょう)',
        visualClue: 'Từng toa tàu xếp liền nhau.',
        soundMnemonic: 'Sha ryô.',
        wackyStory: 'Xe cộ hai đầu.',
        kanjiDeconstruction: ['車 (XA)', '両 (LƯỠNG)'],
        logicalAnchor: 'Bộ phận toa chở khách hoặc phương tiện.',
        collocation: '車両点検 (Kiểm tra toa xe)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-43',
        word: '～号車',
        reading: '～ごうしゃ',
        meaning: 'Toa số...',
        furigana: '～号(ごう)車(しゃ)',
        visualClue: 'Số thứ tự dán ngoài toa tàu.',
        soundMnemonic: 'Gô sha.',
        wackyStory: 'Toa tàu có đánh số.',
        kanjiDeconstruction: ['号 (HIỆU)', '車 (XA)'],
        logicalAnchor: 'Đếm số toa tàu.',
        collocation: '1号車 (Toa số 1)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-44',
        word: 'デッキ',
        reading: 'デッキ',
        meaning: 'Khu vực boong nối giữa các toa tàu',
        furigana: 'デッキ',
        visualClue: 'Chỗ đứng hút thuốc hoặc gọi điện giữa các toa tàu Shinkansen.',
        soundMnemonic: 'Đếk ki.',
        wackyStory: 'Boong tàu.',
        kanjiDeconstruction: [],
        logicalAnchor: 'Khu vực chuyển tiếp, lối đi ra vào cửa.',
        collocation: 'デッキで電話する (Gọi điện thoại ở boong nối)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-45',
        word: '車内',
        reading: 'しゃない',
        meaning: 'Trong tàu, trong xe',
        furigana: '車(しゃ)内(ない)',
        visualClue: 'Phía bên trong không gian hành khách ngồi.',
        soundMnemonic: 'Sha nai.',
        wackyStory: 'Bên trong chiếc xe.',
        kanjiDeconstruction: ['車 (XA)', '内 (NỘI)'],
        logicalAnchor: 'Không gian bên trong phương tiện.',
        collocation: '車内放送 (Phát thanh trong xe)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-46',
        word: '車内販売',
        reading: 'しゃないはんばい',
        meaning: 'Dịch vụ bán hàng trên tàu',
        furigana: '車(しゃ)内(ない)販(はん)売(ばい)',
        visualClue: 'Nhân viên đẩy xe đẩy bán đồ ăn thức uống trên lối đi.',
        soundMnemonic: 'Sha nai han bai.',
        wackyStory: 'Bán hàng rong trong xe.',
        kanjiDeconstruction: ['車 (XA)', '内 (NỘI)', '販 (PHIẾN)', '売 (MẠI)'],
        logicalAnchor: 'Bán hàng lưu động trong tàu.',
        collocation: '車内販売でお弁当を買う (Mua cơm hộp từ dịch vụ bán hàng trên tàu)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-47',
        word: '車掌',
        reading: 'しゃしょう',
        meaning: 'Trưởng tàu, nhân viên soát vé',
        furigana: '車(しゃ)掌(しょう)',
        visualClue: 'Người mặc đồng phục đi dọc toa tàu kiểm tra vé.',
        soundMnemonic: 'Sha shô.',
        wackyStory: 'Bàn tay quản lý chuyến xe.',
        kanjiDeconstruction: ['車 (XA)', '掌 (CHƯỞNG)'],
        logicalAnchor: 'Người điều hành, phụ trách khách hàng trên tàu.',
        collocation: '車掌に尋ねる (Hỏi nhân viên trưởng tàu)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-48',
        word: '停車駅',
        reading: 'ていしゃえき',
        meaning: 'Ga dừng',
        furigana: '停(てい)車(しゃ)駅(えき)',
        visualClue: 'Danh sách các ga mà tàu sẽ ghé lại trên bảng điện tử.',
        soundMnemonic: 'Tê sha ê ki.',
        wackyStory: 'Nhà ga để dừng xe.',
        kanjiDeconstruction: ['停 (ĐÌNH)', '車 (XA)', '駅 (DỊCH)'],
        logicalAnchor: 'Các trạm dừng đón/trả khách.',
        collocation: '次の停車駅 (Ga dừng tiếp theo)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-49',
        word: '終点',
        reading: 'しゅうてん',
        meaning: 'Ga cuối cùng',
        furigana: '終(しゅう)点(てん)',
        visualClue: 'Trạm cuối nơi mọi người phải xuống.',
        soundMnemonic: 'Shuu ten.',
        wackyStory: 'Điểm kết thúc.',
        kanjiDeconstruction: ['終 (CHUNG)', '点 (ĐIỂM)'],
        logicalAnchor: 'Điểm dừng cuối của hành trình.',
        collocation: '終点に到着する (Đến ga cuối cùng)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-50',
        word: '満席',
        reading: 'まんせき',
        meaning: 'Kín chỗ, hết chỗ',
        furigana: '満(まん)席(せき)',
        visualClue: 'Biển báo đỏ hình chữ X chỉ hết vé/ghế.',
        soundMnemonic: 'Man se ki.',
        wackyStory: 'Chỗ ngồi đầy ắp.',
        kanjiDeconstruction: ['満 (MÃN)', '席 (TỊCH)'],
        logicalAnchor: 'Không còn ghế trống.',
        collocation: '予約で満席です (Đã kín chỗ do khách đặt trước)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-51',
        word: '全席禁煙',
        reading: 'ぜんせききんえん',
        meaning: 'Cấm hút thuốc tại toàn bộ các ghế',
        furigana: '全(ぜん)席(せき)禁(きん)煙(えん)',
        visualClue: 'Biển cấm điếu thuốc lá trên toàn xe.',
        soundMnemonic: 'Zen se ki kin en.',
        wackyStory: 'Tất cả ghế ngồi đều cấm khói.',
        kanjiDeconstruction: ['全 (TOÀN)', '席 (TỊCH)', '禁 (CẤM)', '煙 (YÊN)'],
        logicalAnchor: 'Khu vực không được phép hút thuốc.',
        collocation: 'この列車は全席禁煙です (Chuyến tàu này cấm hút thuốc toàn bộ ghế)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-52',
        word: '通話',
        reading: 'つうわ',
        meaning: 'Gọi điện thoại',
        furigana: '通(つう)話(わ)',
        visualClue: 'Người cầm điện thoại áp vào tai.',
        soundMnemonic: 'Tsuu wa.',
        wackyStory: 'Thông qua lời nói.',
        kanjiDeconstruction: ['通 (THÔNG)', '話 (THOẠI)'],
        logicalAnchor: 'Cuộc gọi điện thoại.',
        collocation: 'お席での通話はご遠慮ください (Xin quý khách hạn chế gọi điện thoại tại chỗ ngồi)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-53',
        word: 'まもなく',
        reading: 'まもなく',
        meaning: 'Sắp sửa, chuẩn bị',
        furigana: 'まもなく',
        visualClue: 'Đồng hồ chỉ còn vài giây nữa là đến giờ.',
        soundMnemonic: 'Ma mô na cư.',
        wackyStory: 'Thời gian không còn lâu nữa.',
        kanjiDeconstruction: [],
        logicalAnchor: 'Chỉ một thời gian rất ngắn nữa.',
        collocation: 'まもなく到着します (Sắp đến nơi)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-54',
        word: 'あらかじめご了承ください',
        reading: 'あらかじめりょうしょうください',
        meaning: 'Xin quý khách vui lòng thông cảm/hiểu cho',
        furigana: 'あらかじめご了(りょう)承(しょう)ください',
        visualClue: 'Nhân viên cúi đầu xin lỗi và mong thông cảm trước.',
        soundMnemonic: 'A ra ca ji mê gô ryô shô cư đa sai.',
        wackyStory: 'Biết trước và đồng ý.',
        kanjiDeconstruction: ['了 (LIỄU)', '承 (THỪA)'],
        logicalAnchor: 'Lời nói mong muốn sự lượng thứ trước sự việc sắp diễn ra.',
        collocation: '遅れる場合がございますので、あらかじめご了承ください (Có trường hợp đến trễ, xin quý khách thông cảm)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-55',
        word: '忘れ物',
        reading: 'わすれもの',
        meaning: 'Đồ bỏ quên, đồ thất lạc',
        furigana: '忘(わす)れ物(もの)',
        visualClue: 'Một chiếc ô bị bỏ lại trên tàu.',
        soundMnemonic: 'Wa sư rê mô nô.',
        wackyStory: 'Đồ vật quên mất.',
        kanjiDeconstruction: ['忘 (VONG)', '物 (VẬT)'],
        logicalAnchor: 'Tài sản bị để quên.',
        collocation: '忘れ物に注意する (Chú ý đồ bỏ quên)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-56',
        word: 'カーディガン',
        reading: 'カーディガン',
        meaning: 'Áo khoác len mỏng',
        furigana: 'カーディガン',
        visualClue: 'Chiếc áo khoác len có cúc cài cài.',
        soundMnemonic: 'Ca đi gan.',
        wackyStory: 'Áo khoác ngoài.',
        kanjiDeconstruction: [],
        logicalAnchor: 'Trang phục giữ ấm nhẹ.',
        collocation: 'カーディガンを羽織る (Khoác áo cardigan)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-57',
        word: '奥',
        reading: 'おく',
        meaning: 'Bên trong, góc sâu',
        furigana: '奥(おく)',
        visualClue: 'Góc phòng xa nhất so với cửa ra vào.',
        soundMnemonic: 'Ô cư.',
        wackyStory: 'Góc kẹt.',
        kanjiDeconstruction: ['奥 (ÁO)'],
        logicalAnchor: 'Vị trí khuất sâu bên trong.',
        collocation: '窓側の奥の席 (Ghế trong góc phía cửa sổ)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-58',
        word: '洗面台',
        reading: 'せんめんだい',
        meaning: 'Bồn rửa mặt',
        furigana: '洗(せん)面(めん)台(だい)',
        visualClue: 'Bồn rửa có vòi nước và gương.',
        soundMnemonic: 'Sen men đai.',
        wackyStory: 'Cái bệ để rửa mặt.',
        kanjiDeconstruction: ['洗 (TẨY)', '面 (DIỆN)', '台 (ĐÀI)'],
        logicalAnchor: 'Khu vực vệ sinh cá nhân.',
        collocation: '洗面台に忘れる (Bỏ quên trên bồn rửa mặt)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-59',
        word: '特徴',
        reading: 'とくちょう',
        meaning: 'Đặc trưng, đặc điểm nhận dạng',
        furigana: '特(とく)徴(ちょう)',
        visualClue: 'Đặc điểm dễ nhận biết của đồ vật.',
        soundMnemonic: 'Tô cư chô.',
        wackyStory: 'Đặc tính tiêu biểu.',
        kanjiDeconstruction: ['特 (ĐẶC)', '徴 (TRƯNG)'],
        logicalAnchor: 'Đặc điểm riêng biệt.',
        collocation: 'かばんの特徴 (Đặc điểm của chiếc cặp)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-60',
        word: '気が付く',
        reading: 'きがつ',
        meaning: 'Nhận ra',
        furigana: '気(き)が付(つ)く',
        visualClue: 'Bóng đèn lóe sáng trên đầu.',
        soundMnemonic: 'Ki ga tsu cư.',
        wackyStory: 'Tinh thần phát giác.',
        kanjiDeconstruction: ['気 (KHÍ)', '付 (PHÓ)'],
        logicalAnchor: 'Nhận biết, nhớ ra điều gì.',
        collocation: '帰りの新幹線の中で気が付きました (Nhận ra khi đang ở trên Shinkansen lúc về)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-61',
        word: '問い合わせる',
        reading: 'といあわせる',
        meaning: 'Hỏi thăm, liên hệ',
        furigana: '問(と)い合(あ)わせる',
        visualClue: 'Gọi điện cho nhân viên nhà ga.',
        soundMnemonic: 'Tô i a wa sê rự.',
        wackyStory: 'Hỏi hợp lại.',
        kanjiDeconstruction: ['問 (VẤN)', '合 (HỢP)'],
        logicalAnchor: 'Liên hệ để xác minh thông tin.',
        collocation: '駅に問い合わせる (Liên hệ với nhà ga hỏi thăm)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-62',
        word: '宅配便',
        reading: 'たくはいびん',
        meaning: 'Dịch vụ chuyển phát tận nhà',
        furigana: '宅(たく)配(はい)便(びん)',
        visualClue: 'Chiếc xe tải chở hàng và nhân viên giao hàng.',
        soundMnemonic: 'Ta cư hai bin.',
        wackyStory: 'Phân phối tiện lợi đến nhà.',
        kanjiDeconstruction: ['宅 (TRẠCH)', '配 (PHỐI)', '便 (TIỆN)'],
        logicalAnchor: 'Dịch vụ vận chuyển.',
        collocation: '宅配便で送る (Gửi bằng dịch vụ chuyển phát)',
        lessonId: 'lesson-10'
    },
    {
        id: 'vocab-10-63',
        word: '着払い',
        reading: 'ちゃくばらい',
        meaning: 'Thanh toán cước khi nhận hàng',
        furigana: '着(ちゃく)払(ばら)い',
        visualClue: 'Người nhận đưa tiền cho shipper.',
        soundMnemonic: 'Cha cư ba rai.',
        wackyStory: 'Đến nơi mới trả tiền.',
        kanjiDeconstruction: ['着 (TRƯỚC)', '払 (PHẤT)'],
        logicalAnchor: 'Người nhận trả phí vận chuyển.',
        collocation: '着払いの宅配便で送る (Gửi chuyển phát người nhận trả cước)',
        lessonId: 'lesson-10'
    }
];